### ISSUE TITLE
Feature Request: Support custom attributes in generated project

### ISSUE THREAD

**Issue by sebastianv1** [MobileNativeFoundation/rules_xcodeproj#1342]
We'd like to set the `ORGANIZATIONNAME` attribute in the generated pbxproj file (this is used in populating the new file header template).

I could imagine a new rule attribute (named `attributes`) where we set key value value pairs, but would love to hear others' thoughts.

**Comment by brentleyjones** [comment]
This is now supported with the [`organization_name`](https://github.com/MobileNativeFoundation/rules_xcodeproj/blob/1.18.0/docs/bazel.md#project_options-organization_name) attribute on `project_options`.
