### ISSUE TITLE
Bug: ANDROID_NDK_HOME environment variable not inherited

### ISSUE THREAD

**Issue by pswaminathan** [MobileNativeFoundation/rules_xcodeproj#1451]
## Describe the bug

When including Android NDK repository in WORKSPACE without a path set, Bazel looks at the value of `ANDROID_NDK_HOME`. Xcode fails to build because it does not inherit this environment variable.

## Reproduction steps
1. Add an Android NDK repository rule, e.g.:
```
android_ndk_repository(
    name = "androidndk",
    api_level = 25,
)
```
2. Set `ANDROID_NDK_HOME` envvar
3. Run xcodeproj to generate project
4. Launch Xcode pointed to rules_xcodeproj-generated project
5. Fails at analysis

## Versions
- Bazel: 6.0.0rc1
- rules_xcodeproj: 0.10.2
- rules_apple:
- rules_swift:

**Comment by brentleyjones** [comment]
This is now supported via the [`bazel_env`](https://github.com/MobileNativeFoundation/rules_xcodeproj/blob/1.18.0/docs/bazel.md#xcodeproj-bazel_env) attribute.

**Comment by pswaminathan** [comment]
@brentleyjones what is supported in the `bazel_env` attribute? For instance, a value of 

```
    bazel_env = {
        "ANDROID_HOME": "$HOME/Library/Android/sdk",
        "ANDROID_NDK_HOME": "$HOME/Library/Android/sdk/ndk/26.2.11394342",
    },
```

fails with:

```
ERROR: Analysis of target '@rules_xcodeproj_generated//generator/src/airborne/iOS/xcodeproj:xcodeproj' failed; build aborted: The repository's path is "$HOME/Library/Android/sdk" (absolute: "/Users/p/Code/ergatta/a2/$HOME/Library/Android/sdk") but a symlink could not be created for it, because: /Users/p/Code/ergatta/a2/$HOME/Library/Android/sdk (No such file or directory)
```

**Comment by brentleyjones** [comment]
Try `~` instead of `$HOME`. Env variables should work though, and I'll look at that next week when I'm back to work.

**Comment by pswaminathan** [comment]
Thanks! Sorry to interrupt while you're out; the following can be ignored until you get back.

`~` fails with the same message. Env vars generally would indeed be nice, because it would be nice to have it simply be e.g. `"ANDROID_HOME": "$ANDROID_HOME"`

**Comment by brentleyjones** [comment]
By setting the value as `None`, it will do that.

**Comment by brentleyjones** [comment]
https://github.com/MobileNativeFoundation/rules_xcodeproj/pull/2983
