### ISSUE TITLE
Feature Request: Support `ipa_post_processor `

### ISSUE THREAD

**Issue by erikkerber** [MobileNativeFoundation/rules_xcodeproj#1462]
I have to imagine this would involve converting the script behind that attribute into a `post_build_script`.

**Comment by brentleyjones** [comment]
> I have to imagine this would involve converting the script behind that attribute into a `post_build_script`.

Yes, which means we would need to support those in BwX mode.

But also, we would need to re-sign properly, or ensure this happens before Xcode signs the app, the same as Bazel does after running `ipa_post_processor`.
