### ISSUE TITLE
Feature Request: Hide extraneous targets created by `rules_ios` macros

### ISSUE THREAD

**Issue by luispadron** [MobileNativeFoundation/rules_xcodeproj#1724]
`rules_ios` seems to create a target `_objc` and/or `_swift` for each framework which in turn causes them to show up in the Xcode target navigator.

It would be nice to support hiding these somehow as a default.

`rules_xcodeproj`: 9ab3f0d3751eada941e3d1207b392c6e9b8deb01

<img width="331" alt="Screenshot 2023-02-01 at 2 47 36 PM" src="https://user-images.githubusercontent.com/13840545/216148026-a8b0e929-0c70-4f6d-aa94-3be56ac9b534.png">

**Comment by brentleyjones** [comment]
This would require changes to target merging. Not sure if it's possible or not, but I can look into it.

As for just not creating the schemes, custom schemes or eventually https://github.com/buildbuddy-io/rules_xcodeproj/issues/857 would prevent the schemes from being created.

**Comment by mattrobmattrob** [comment]
As mentioned in the Bazel Slack, super simple replication for this issue in https://github.com/mattrobmattrob/rules_xcodeproj_playground/tree/mr/rules_ios.swift.fwk (just `bazel run :Project` to exercise `rules_xcodeproj`).

Actively working on this.

**Comment by mattrobmattrob** [comment]
This isn't necessarily done but should now have `ios_unit_test`/`ios_ui_test` merged. Next up, would be the actual intra-graph merges for `apple_framework`'s _swift and _objc suffixed targets.

**Comment by brentleyjones** [comment]
@luispadron is this addressed with incremental generation?

**Comment by luispadron** [comment]
Yes! I think we can close it 🚀

**Comment by brentleyjones** [comment]
Thanks! I'll tie it to that milestone and close it then.
