### ISSUE TITLE
Bug: Focused rules_ios targets do not show top level targets in Xcode

### ISSUE THREAD

**Issue by yongjincho92** [MobileNativeFoundation/rules_xcodeproj#1790]
## Describe the bug
When using focused_targets functionality on rules_ios targets, the top level rules_ios target is not visible from Xcode app.

##
Reproduction steps
1. Download and extract the zip file [Repro.zip](https://github.com/buildbuddy-io/rules_xcodeproj/files/10845583/Repro.zip)
2. `bazel run //:App.xcodeproj` and check that source files in the `App` target are visible from Xcode 
3. `bazel run //:FocusedApp.xcodeproj` and check that source files in the `App` target are not visible from Xcode 

## Expected behavior
App/main.m is visible from Xcode 

## Versions
- Bazel: 6.0.0
- rules_xcodeproj: tip of main branch 
- rules_apple: transitively pulled in https://github.com/bazel-ios/rules_ios/blob/master/rules/repositories.bzl
- rules_swift: transitively pulled in https://github.com/bazel-ios/rules_ios/blob/master/rules/repositories.bzl

## Additional context
This issue doesn't occur to targets that do not use rules_ios rules. (simple rules_apple targets seem to work fine).

**Comment by brentleyjones** [comment]
Probably related to https://github.com/buildbuddy-io/rules_xcodeproj/issues/1724. I'll look soon.

**Comment by brentleyjones** [comment]
@mattrobmattrob This is another case where handling `.dep_middleman` better will fix things.

@yongjincho92 This is related to #1742, and we are working on a general solution to it.

**Comment by mattrobmattrob** [comment]
AFAIK this is fixed on the `main` of the repo. Please reopen if you disagree, @yongjincho92.

|`App.xcodeproj`|`FocusedApp.xcodeproj`
|---|---|
|<img width="1818" alt="Screenshot 2023-04-27 at 4 38 21 PM" src="https://user-images.githubusercontent.com/5728070/235005947-fa53b612-6535-4848-b4b1-5354f4d95f64.png">|<img width="1819" alt="Screenshot 2023-04-27 at 4 39 08 PM" src="https://user-images.githubusercontent.com/5728070/235005950-226371ac-5c92-431a-a760-69cc8d6bafd6.png">|
