### ISSUE TITLE
Bug: Files generated via swift_proto_library are not accessible on Xcode file tree

### ISSUE THREAD

**Issue by ra1028** [MobileNativeFoundation/rules_xcodeproj#1837]
## Describe the bug

Maybe, this should be classified as a feature request rather than a bug.
Files generated via swift_proto_library are not appeared in the `Bazel Generated Files` section of the Xcode file tree.
Therefore, jump-to-definition and autocomplete work well, but file search and syntax highlighting do not.

Probably, this is related to https://github.com/buildbuddy-io/rules_xcodeproj/issues/1744

## Reproduction steps

Define swift_proto_library target like below, and add it to the `xcodeproj`.

```python
proto_library(
    name = "example_proto",
    srcs = glob([
        "*.proto",
    ]),
)

swift_proto_library(
    name = "example_proto_swift",
    deps = [":example_proto"],
) 

swift_library(
    name = "example_lib",
    ...
    deps = [":example_proto_swift"]  ,   
)

ios_unit_test(
    name = "example_test",
    deps = [":example_lib"],
)

xcodeproj(
   name = "xcodeproj",
   ...
   top_level_targets = [
       top_level_target(":example_test", target_environments = ["simulator"]),
   ],
)
```

## Expected behavior

When an Xcode project is generated, rules_xcodeproj places the files to be generated in `xxx/bin/external/yyyy` under `Bazel Generated Files` as missing files, and then to be available after you build the target.
All the following Xcode features are enabled for the generated files and symbols.

- Jump to definition
- Auto completion
- Syntax highlighting
- Xcode file search
- Xcode text search

## Versions
- Bazel: 6.0.0-pre.20220804.3
- rules_xcodeproj: 1.2.0
- rules_apple: d04edf4136b4818662d7126582ec257aee372339 (not a release tag for some reason)
- rules_swift: 6153a848f747e90248a8673869c49631f1323ff3 (not a release tag for some reason)

## Additional context

We also have a target defined using [rules_proto_grpc](https://github.com/rules-proto-grpc/rules_proto_grpc), and the files generated by it appear on the Xcode file tree. It has a rule just to compile the protos and then the files are consumed by the official `swift_library` rule.

**Comment by thii** [comment]
Addressed by https://github.com/MobileNativeFoundation/rules_xcodeproj/pull/2484.
