### ISSUE TITLE
Bug: "argument list too long" with large `EXCLUDED_SOURCE_FILE_NAMES` build setting

### ISSUE THREAD

**Issue by yongjincho92** [MobileNativeFoundation/rules_xcodeproj#1854]
## Describe the bug
Xcode build fails due to error "/bin/sh argument list too long"

## Reproduction steps
1. On a large iOS project using `rules_ios`, run `rules_xcodeproj`'s `xcodeproj` with `focused_targets` attribute (pass the top level target to `focused_targets`). 
2. Open Xcode and run build (command + b)

## Expected behavior
Build completes successfully 

## Versions
- Bazel: 6.0.0
- rules_xcodeproj: 1.2.0
- rules_apple: n/a
- rules_swift: n/a 

## Additional context
I noted two things in the generated `project.pbxproj` file:
1. Both `EXCLUDED_SOURCE_FILE_NAMES` and `INCLUDED_SOURCE_FILE_NAMES` build settings values have too long values resulting to error `/bin/sh argument list too long`. 
2. Most of the files included in the build settings values `EXCLUDED_SOURCE_FILE_NAMES` and `INCLUDED_SOURCE_FILE_NAMES` are `.strings` resource files.

**Comment by brentleyjones** [comment]
https://github.com/buildbuddy-io/rules_xcodeproj/commit/71bd29e747a64aa9d9c815e307de8fd29bda0b8f should fix your specific issue while using BwB mode. For projects where BwX mode works, there is still an issue of many resource files causing an issue. I'm trying to think of a way address that.

**Comment by brentleyjones** [comment]
@yongjincho92 Did the change to use compiler param files fix this for you?

**Comment by yongjincho92** [comment]
@brentleyjones Yeah it does fix the issue! Thanks
