### ISSUE TITLE
Bug: focused_targets doesn't work properly in 1.3.1 or later

### ISSUE THREAD

**Issue by ra1028** [MobileNativeFoundation/rules_xcodeproj#1912]
### What happened?

This error was introduced after version 1.3.1 and doesn't occur in 1.3.0.
All targets specified in the `focused_targets` are certainly transitive dependencies of the targets listed in `top_level_targets`, but project generation fails with the following error.

```sh
ERROR: /Users/xxx/.rules_xcodeproj/xcodeproj-sim_arm64-Dev-Debug/BUILD:6:10: in xcodeproj rule //.rules_xcodeproj/xcodeproj-sim_arm64-Dev-Debug:xcodeproj-sim_arm64-Dev-Debug:
Traceback (most recent call last):
	File "/Users/xxx/bazel-output-base/rules_xcodeproj/build_output_base/external/rules_xcodeproj/xcodeproj/internal/xcodeproj_rule.bzl", line 1458, column 25, in _xcodeproj_impl
		) = _process_targets(
	File "/Users/xxxs/bazel-output-base/rules_xcodeproj/build_output_base/external/rules_xcodeproj/xcodeproj/internal/xcodeproj_rule.bzl", line 333, column 13, in _process_targets
		fail("""\
Error in fail: `focused_targets` contains target(s) that are not transitive dependencies of the targets listed in `top_level_targets`: ["//target:name"]

Are you using an `alias`? `focused_targets` requires labels of the actual targets.
```

### Reproduction steps

- Use version 1.3.1 or later.
- List all top-level targets in the repository in `top_level_targets`.
- List some of their transitive dependencies in `focused_targets`.
- Perform project generation.

### Expected behavior

Successfully generate a focused project.

### rules_xcodeproj version

1.3.2 or 1.3.1

### Bazel version

6.0.0-pre.20220804.3

### rules_apple version

d04edf4136b4818662d7126582ec257aee372339

### rules_swift version

6153a848f747e90248a8673869c49631f1323ff3

**Comment by brentleyjones** [comment]
I wasn't able to quickly reproduce this. I'll keep trying. A reproduction project would help.

**Comment by brentleyjones** [comment]
I reproduced it with that old Bazel version. We don't technically support the rolling releases between LTS releases, but I'll see if I can fix this regardless.

**Comment by brentleyjones** [comment]
Looks like it's broken in Bazel 5 as well. Fix incoming.

**Comment by ra1028** [comment]
Thanks!

**Comment by ra1028** [comment]
@brentleyjones 

I noticed that target focusing in rules_xcodeproj 1.3.3 behaves differently than in 1.3.0.
My usage of target focusing is to filter out targets other than `ios_framework` in Xcode. It's a workaround to get SwiftUI previews working as described [here](https://github.com/MobileNativeFoundation/rules_xcodeproj/issues/1384).
With 1.3.0, if Xcode contained only ios_framework, the corresponding files were listed in the `Compile Sources` of the corresponding Xcode target, but in 1.3.3, only `_CompileStub_.m` appears, and Xcode doesn't show source files in the file tree anymore.

**Comment by brentleyjones** [comment]
Interesting, can you open up a new issue, ideally with a small repro? I'll get this fixed.

**Comment by brentleyjones** [comment]
I believe this commit might be the break: https://github.com/MobileNativeFoundation/rules_xcodeproj/commit/ed31d6916858f3099ba1a95750f5309913370a8d

cc: @mattrobmattrob

**Comment by brentleyjones** [comment]
I will. And when you get back feel free to put another change in that does what you intended while still accounting for this case :+1:.

**Comment by ra1028** [comment]
@brentleyjones 
Thanks. I'll check it later on. Would you still like me to open up a new issue for it?

**Comment by brentleyjones** [comment]
No, that's fine.
