### ISSUE TITLE
Bug: Test suite targets not supported as top level targets

### ISSUE THREAD

**Issue by thiagohmcruz** [MobileNativeFoundation/rules_xcodeproj#1956]
### Description

If you hit [this code path](https://github.com/bazel-ios/rules_ios/blob/master/rules/test.bzl#L128) in `rules_ios` you'll get errors during project generation:
```sh
ERROR: /private/var/tmp/_bazel_thiago/122885c1fe4a2c6ed7635584956dfc9d/rules_xcodeproj/build_output_base/external/rules_xcodeproj_generated/generator/BUILD:6:10: in xcodeproj rule @rules_xcodeproj_generated//generator:generator: 
Traceback (most recent call last):
        File "/private/var/tmp/_bazel_thiago/122885c1fe4a2c6ed7635584956dfc9d/rules_xcodeproj/build_output_base/external/rules_xcodeproj/xcodeproj/internal/xcodeproj_rule.bzl", line 1390, column 26, in _xcodeproj_impl
                i = [_process_dep(dep) for dep in targets]
        File "/private/var/tmp/_bazel_thiago/122885c1fe4a2c6ed7635584956dfc9d/rules_xcodeproj/build_output_base/external/rules_xcodeproj/xcodeproj/internal/xcodeproj_rule.bzl", line 121, column 13, in _process_dep
                fail("""
Error in fail: 
'@//tests/macos/xcodeproj:Single-Application-RunnableTestSuite' is not a top-level target, but was listed in `top_level_targets`. Only list top-level targets (e.g. binaries, apps, tests, or distributable frameworks) in `top_level_targets`. Schemes and `focused_targets`/`unfocused_targets` can refer to dependencies of targets listed in `top_level_targets`, and don't need to be listed in `top_level_targets` themselves.

If you feel this is an error, and `test_suite` targets should be recognized as top-level targets, file a bug report here: https://github.com/MobileNativeFoundation/rules_xcodeproj/issues/new?template=bug.md
```

### Reproduction steps

* Checkout this branch: [thiago/repro-test-suite-not-supported-rules-xcodeproj](https://github.com/bazel-ios/rules_ios/compare/master...thiago/repro-test-suite-not-supported-rules-xcodeproj)
* Run `bazel run tests/ios/app:foo`
* You should hit the same err reported here

### Expected behavior

[ios_unit_test_suite](https://github.com/bazelbuild/rules_apple/blob/master/doc/rules-ios.md#ios_unit_test_suite) and [ios_ui_test_suite](https://github.com/bazelbuild/rules_apple/blob/master/doc/rules-ios.md#ios_ui_test_suite) can be passed as top level targets.

### rules_xcodeproj version

1.3.3

### Xcode version

14.2

### Bazel version

6.0.0

### rules_apple version

935d5ad80300578f35833db26f124f20aeda9cba

### rules_swift version

17e20f7edf27e647f1b45f11ed75d51c17820c3b

### Additional information

Happy to take this myself, any feedback and general guidance appreciated on how to approach adding support for it.

**Comment by brentleyjones** [comment]
I think that if this https://github.com/MobileNativeFoundation/rules_xcodeproj/blob/ca6e4bda6633cbe7e11edc229125375921cd5069/xcodeproj/internal/xcodeprojinfo.bzl#L70-L92

is modified to pass through for `test_suite`s, it should end up working (at least, all of the depended on test targets should end up in the project). I'm not sure about listing these targets in custom schemes and stuff though.

**Comment by thiagohmcruz** [comment]
Cool thx @brentleyjones adding `test_suite` there indeed generates a project successfully, I'll take a look at custom schemes next

**Comment by thiagohmcruz** [comment]
FYI @brentleyjones also tested this in the incremental generator and it's fixed there.

**Comment by mattrobmattrob** [comment]
That incremental generator just keeps on giving. Great job, @brentleyjones!
