### ISSUE TITLE
Bug: Index compilation for a source file in a objc_library with implementation_deps fails 

### ISSUE THREAD

**Issue by yongjincho92** [MobileNativeFoundation/rules_xcodeproj#1963]
### Description

At Snap, we added a change (https://github.com/bazelbuild/bazel/pull/17962) in Bazel fork to support `implementation_deps` for `objc_library` rule. 

We have found that rules_xcodeproj generated Xcode fails to compile a source file that imports a header defined in its implementation_deps. 

Say, ATest is a unit test target and depends on target A. And the target A is an implementation deps of ATest. Building ATest works fine, however, opening `TestA.m` in Xcode editor tap triggers Xcode to index-compile the source file, which fails because path to A.h is not passed as a copt. 

### Reproduction steps

1. Download repro project from https://drive.google.com/file/d/1iixYoxc6Tek8q-VlIqF6udS8_mexCbqs/view?usp=share_link 
2. Extract it and go into dir 
3. run `./bazel run //lib:A.xcodeproj`  (bazel binary bundled together has change https://github.com/bazelbuild/bazel/pull/17962) 
4. run `open lib/A.xcodeproj` 
5. open `TestA.m` and check in Xcode's Index log that the compilation failed due to missing "A.h"

### Expected behavior

When opening TestA.m, Xcode should be able to find "A.h" and compile `TestA.m` successfully. 

### rules_xcodeproj version

1.3.2

### Xcode version

14.1

### Bazel version

upstream/main (b24930f6f90934a0665c7454e12cc6c4e4ecc7b3) + https://github.com/bazelbuild/bazel/pull/17962

**Comment by brentleyjones** [comment]
Thanks for the repro. I'll look into this soon!

**Comment by yongjincho92** [comment]
the bazel binary I bundled together is arm64 executable, so let me know if you need intel cpu version.

**Comment by brentleyjones** [comment]
Apple Silicon is perfect, thanks.
