### ISSUE TITLE
Bug: Source files for objc_library (implementaion_deps of top level target) is not visible on Xcode 

### ISSUE THREAD

**Issue by yongjincho92** [MobileNativeFoundation/rules_xcodeproj#1964]
### Description

At Snap, we added a change (https://github.com/bazelbuild/bazel/pull/17962) in Bazel fork to support implementation_deps for objc_library rule.

We have found that rules_xcodeproj generated Xcode doesn't show source files of a target that is an implementation deps of a top level target.

Say, `ATest` is a unit test target and a top level target and depends on target `A`. And the target `A` is an implementation deps of `ATest`. In Xcode project navigator, source file `A.m` is not visible. 

### Reproduction steps

1. Download repro project from https://drive.google.com/file/d/1iixYoxc6Tek8q-VlIqF6udS8_mexCbqs/view?usp=share_link 
2. Extract it and go into dir 
3. run `./bazel run //lib:A.xcodeproj`  (bazel binary bundled together has change https://github.com/bazelbuild/bazel/pull/17962) 
4. run `open lib/A.xcodeproj` 
5. Observe that A.m is not visible on Xcode 
<img width="1394" alt="Screenshot 2023-04-04 at 4 41 07 PM" src="https://user-images.githubusercontent.com/49507839/229945813-fc75e012-18d8-4fcb-b55c-c65924563043.png">

### Expected behavior

1. change `lib/BUILD.bazel` content 

from 
```
objc_library(
    name = "ATests_lib",
    srcs = glob(["Tests/*.m"]),
    # if you change this to `deps`, indexing will work
    implementation_deps = [":A"],
)
```

after 
```
objc_library(
    name = "ATests_lib",
    srcs = glob(["Tests/*.m"]),
    # if you change this to `deps`, indexing will work
    deps = [":A"],
)
```

2. re-run `./bazel run //lib:A.xcodeproj`
3. observe that A.h and A.m are visible on Xcode 
<img width="1393" alt="Screenshot 2023-04-04 at 4 43 07 PM" src="https://user-images.githubusercontent.com/49507839/229946046-099c06ea-1c74-4ddd-9908-ec97966e877c.png">

### rules_xcodeproj version

1.3.2

### Xcode version

14.1

### Bazel version

upstream/main (b24930f6f90934a0665c7454e12cc6c4e4ecc7b3) + https://github.com/bazelbuild/bazel/pull/17962

### Additional information

bundled bazel binary is for apple silicon

**Comment by yongjincho92** [comment]
hmm, looks like it's simply resolved by this change(https://github.com/MobileNativeFoundation/rules_xcodeproj/pull/1933) , which we use on our main repo, but I didn't have it in my repro setup 

```
@@ -91,6 +91,7 @@ def _default_automatic_target_processing_aspect_impl(target, ctx):
     elif ctx.rule.kind == "objc_library":
         xcode_targets = {
             "deps": [target_type.compile, None],
+            "implementation_deps": [target_type.compile],
             "runtime_deps": [target_type.compile],
         }
         non_arc_srcs = ["non_arc_srcs"]
```

**Comment by brentleyjones** [comment]
Cool. Can you address the CI issues on #1933 and we can merge it?

**Comment by yongjincho92** [comment]
Sure.
