### ISSUE TITLE
Feature Request: Select scheme for top level target in Xcode by default

### ISSUE THREAD

**Issue by yongjincho92** [MobileNativeFoundation/rules_xcodeproj#1970]
**Background** 
It'd be better user experience if the generated Xcode project starts with top level target scheme selected. 

**Repro**
1. in rules_xcodeproj repo, go to rules_ios example dir 
2. `bazelisk run //:xcodeproj`
3. open generated Xcode project 
4. Observe the selected scheme in Xcode by default 

**Expected Result**
1. Schemes corresponding to top level target passed to xcodeproj rule is selected by default 

**Actual Result**
1. Scheme that is alphabetically coming first is selected by default

**Comment by brentleyjones** [comment]
I guess we need to tightly define what the exact order should be, then we can implement it. Maybe sorting by type (top-level, then non-top-level), and sub-sort alphabetically?

**Comment by yongjincho92** [comment]
>sorting by type (top-level, then non-top-level), and sub-sort alphabetically?

That sounds reasonable to me.

**Comment by brentleyjones** [comment]
We would need to create and replace the `PROJECT.xcodeproj/xcuserdata/$USER.xcuserdatad/xcschememanagement.plist` file in `installer.sh`. Deleting this file (or not having one, which is the default) will cause Xcode to alphabetize the list. the file looks like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>SchemeUserState</key>
	<dict>
		<key>generator.xcscheme_^#shared#^_</key>
		<dict>
			<key>orderHint</key>
			<integer>1</integer>
		</dict>
		<key>swiftc.xcscheme_^#shared#^_</key>
		<dict>
			<key>orderHint</key>
			<integer>0</integer>
		</dict>
	</dict>
</dict>
</plist>
```

So we would need to generate one with the `orderHint` set correctly (as that is what determines the order in the list).

As for changing which one is selected... if the project hasn't been opened before, it will be the first one, so the above should be enough. I think that's probably going to be desired, as we don't want that to change each time the project is generated. If we did want to change that though, we could try to modify `PROJECT.xcodeproj/project.xcworkspace/xcuserdata/$USER.xcuserdatad/UserInterfaceState.xcuserstate`, the `IDERunContextRecentsLastUsedRunDestinationBySchemeKey` might affect that?

**Comment by yongjincho92** [comment]
ah that's a good point! I think making sure the desired scheme to be selected before the project is opened is good enough for most use case.
