### ISSUE TITLE
Bug: All BUILD files appear in project with target focusing (regression)

### ISSUE THREAD

**Issue by andre-alves** [MobileNativeFoundation/rules_xcodeproj#1993]
### Description

I'm testing `main` and noted a possible regression after e19098fc786ac8a41bad2aeaa0930f31da64fed3 in regards to focus mode.

rules_xcodeproj is adding BUILD files for all targets in the generated project, even for targets not specified in `focused_targets`. 

| Before e19098fc786ac8a41bad2aeaa0930f31da64fed3  | After e19098fc786ac8a41bad2aeaa0930f31da64fed3 |
| ------------- | ------------- |
| <img width="263" alt="no-bug" src="https://user-images.githubusercontent.com/7773955/230775735-ddcd9d13-8208-4299-905d-c37ed0fd05af.png">  | <img width="303" alt="bug" src="https://user-images.githubusercontent.com/7773955/230775741-64c1b28a-0dba-4462-8e3c-22f80ccc85a0.png">  |

### Reproduction steps

Apply this [diff](https://github.com/andre-alves/rules_xcodeproj/commit/97f754c9c634b04019ee02104572b6975b3c0152) to the `integration` sample of this repo.

```
cd examples/integration
bazel run //:xcodeproj-sim_arm64
xed .
```

### Expected behavior

The generated project contains `BUILD` files only from `focused_targets`.

### rules_xcodeproj version

458270d8f90402af0000962267d691e9394cd55e

### Xcode version

14.1

### Bazel version

6.1.1

### rules_apple version

2.2.0

### rules_swift version

1.7.1

**Comment by brentleyjones** [comment]
Thanks for the repro. I'll get this fixed early next week before the 1.4.0 release.

**Comment by brentleyjones** [comment]
Needing to use `build_mode = "bazel"` in your repro is another issue I'll have to separately fix.

**Comment by andre-alves** [comment]
Thanks for the quick fix!
