### ISSUE TITLE
Bug: Focused project does not include source files for rules_ios project

### ISSUE THREAD

**Issue by AngelaGuardia** [MobileNativeFoundation/rules_xcodeproj#2021]
### Description

Generating a focused project for a `rules_ios` project does not bring in source files to Xcode.

### Reproduction steps

- Checkout this branch: [aguardia/repro-focused-no-including-source-files-rules-xcodeproj](https://github.com/bazel-ios/rules_ios/compare/aguardia/repro-focused-no-including-source-files-rules-xcodeproj?expand=1)
- Run `bazel run //tests/ios/app:foo && open foo.xcodeproj`
- The Xcode project does contain the expected `App.swift` source file inside the `tests/ios/app` directory

### Expected behavior

- The Xcode project should contain the `App.swift` source file inside the `tests/ios/app` directory

### rules_xcodeproj version

1.3.3

### Xcode version

14.2

### Bazel version

6.0.0

### rules_apple version

935d5ad80300578f35833db26f124f20aeda9cba

### rules_swift version

17e20f7edf27e647f1b45f11ed75d51c17820c3b

### Additional information

The source file import seems to be skipped at [this point](https://github.com/MobileNativeFoundation/rules_xcodeproj/blob/c4c1959e7be8e25da5ebedbd910f135ac6bf23ee/xcodeproj/internal/xcodeproj_rule.bzl#L124) in the code. The condition is met because`rules_ios` creates additional `//tests/ios/app:foo_swift` and `//tests/ios/app:foo_objc` targets.

**Comment by thiagohmcruz** [comment]
cc @mattrobmattrob

**Comment by brentleyjones** [comment]
> 7967b372bd1777214ce65c87a82ac0630150b7504b443de0315ea52e45758e0c

I don't see that commit. Can you link to it from GitHub for me?

**Comment by thiagohmcruz** [comment]
> > 7967b372bd1777214ce65c87a82ac0630150b7504b443de0315ea52e45758e0c
> 
> I don't see that commit. Can you link to it from GitHub for me?

I think that's 1.3.3, cc @AngelaGuardia to confirm

**Comment by mattrobmattrob** [comment]
With the latest commit (so essentially 1.4.0), the target is merged properly without any focused targets:

<img width="1751" alt="Screenshot 2023-04-12 at 2 54 51 PM" src="https://user-images.githubusercontent.com/5728070/231582977-d0aa94ed-da04-4b39-a529-5a71bbea9083.png">

But still doesn't work when focused as in the branch:

<img width="1751" alt="Screenshot 2023-04-12 at 2 56 06 PM" src="https://user-images.githubusercontent.com/5728070/231583170-838ec9e3-e1dd-4723-9f8f-198b29c7a540.png">

**Comment by mattrobmattrob** [comment]
The branch's version is `1.3.3`:

```Starlark
http_archive(
    name = "rules_xcodeproj",
    sha256 = "7967b372bd1777214ce65c87a82ac0630150b7504b443de0315ea52e45758e0c",
    url = "https://github.com/MobileNativeFoundation/rules_xcodeproj/releases/download/1.3.3/release.tar.gz",
)
```

Linked version is actually the `sha256` value. 👍

**Comment by thiagohmcruz** [comment]
Btw @mattrobmattrob random thought: should add all "target merging" related issues to a GH project so we can get a sense of how far we are from a "release candidate" version?

Not meaning to put pressure on this at all, just trying to think of a way for us to organize the remaining work a little bit better

**Comment by mattrobmattrob** [comment]
> Btw @mattrobmattrob random thought: should add all "target merging" related issues to a GH project so we can get a sense of how far we are from a "release candidate" version?

If you think it's valuable, sure. For me, I'm essentially entirely focused on the `ios_unit_test`/`ios_ui_test` merging case since that's what populates the test navigator with the parsing Xcode does. Otherwise, I'm less concerned/focused but my work should also lay some of the foundation for mixed-language-framework (`apple_framework_packaging` or otherwise) merging as well.
