### ISSUE TITLE
Bug: Failing to generate project when WORKSPACE includes a git_repository rule

### ISSUE THREAD

**Issue by photex** [MobileNativeFoundation/rules_xcodeproj#2065]
### Description

This is perhaps just a bug in documentation rather than something regarding the project itself, but after adding a git_repository I stopped being able to generate the xcode project:

```
git-lfs filter-process: git-lfs: command not found
```

I feel like this has more to do with sandboxing rather than any part of these rules, but although my .bazelrc disables sandboxing, I guess that doesn't apply to the project generator? Is that correct?

### Reproduction steps

Create a simple bazel project and add a git_repository rule on a test repo that requires git-lfs.

### Expected behavior

I'd just expect things to more or less work as they do with the rest of the build.

### rules_xcodeproj version

1.4.0

### Xcode version

14.3

### Bazel version

6.1.1

### rules_apple version

2.2.0

**Comment by brentleyjones** [comment]
Where is `git-lfs` installed at? This is probably our `PATH` filtering. Can you see if adjusting `PATH` with [xcodeproj.bazel_env](https://github.com/MobileNativeFoundation/rules_xcodeproj/blob/main/docs/bazel.md#xcodeproj-bazel_env) fixes it?

**Comment by mattrobmattrob** [comment]
We're currently using `git_repository` for `rules_apple` without issues so likely to be specific to whatever repo is in question.

**Comment by photex** [comment]
> Where is `git-lfs` installed at? This is probably our `PATH` filtering. Can you see if adjusting `PATH` with [xcodeproj.bazel_env](https://github.com/MobileNativeFoundation/rules_xcodeproj/blob/main/docs/bazel.md#xcodeproj-bazel_env) fixes it?

`which git-lfs` => `/opt/homebrew/bin/git-lfs`

It seems to work to use:

`bazel_env = {"PATH":"/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin"}`

**Comment by brentleyjones** [comment]
I would put homebrew last, to increase hermeticity.

This is working as intended. I’m glad you found a solution.

**Comment by photex** [comment]
One minor suggestion would be a note in the readme perhaps? Or if it’s there then it’s easy to miss. :)

**Comment by brentleyjones** [comment]
`xcodeproj.bazel_path` and `xcodeproj.bazel_env` probably deserve a section in `usage.md`, yeah.
