### ISSUE TITLE
Bug: Unknown target IDs in BwB (regression)

### ISSUE THREAD

**Issue by andre-alves** [MobileNativeFoundation/rules_xcodeproj#2120]
### Description

I've just updated rules_xcodeproj to 1.5.0 (which is much faster now, thank you very much!) and noticed a possible regression when trying to build focused apps inside Xcode (BwB):

<img width="1174" alt="Screenshot 2023-04-26 at 09 10 34" src="https://user-images.githubusercontent.com/7773955/234572012-6a86a43c-6b49-4dc3-b510-6f26ab3e7740.png">

This error doesn't happen in rules_xcodeproj 1.4.0

### Reproduction steps

Apply this [diff](https://github.com/andre-alves/rules_xcodeproj/commit/9ae7d1751b8dd859b892791e89c64879bbea5807) to the integration sample of this repo.

```
cd examples/integration
bazel run //:xcodeproj-sim_arm64
xed .
Build scheme iOSApp
```

_Note: I commented `xcode_configurations` because the error doesn't happen when this argument is provided. Maybe they are related? We don't use `xcode_configurations` in our setup yet._

### Expected behavior

Expected the scheme to build successfully.

### rules_xcodeproj version

1.5.0

### Xcode version

14.1

### Bazel version

6.1.1

### rules_apple version

2.2.0

### rules_swift version

1.7.1

**Comment by brentleyjones** [comment]
Thanks for the repro! I’ll fix this very soon.
