### ISSUE TITLE
plistlib.InvalidFileException: Invalid file

### ISSUE THREAD

**Issue by jalalimehdi** [MobileNativeFoundation/rules_xcodeproj#2125]
### Description

My error is plistlib.InvalidFileException: Invalid file
I used this version [rules_xcodeproj @ 7f600dd](https://github.com/MobileNativeFoundation/rules_xcodeproj/tree/7f600ddd7cb3ebc59c696a4639b84b93267c7b6e)

extensionpointidentifiers_parser.py", line 28, in _main
    plist = plistlib.load(fp)
>>>>
plistlib.py, line 869, in load
    raise InvalidFileException()
plistlib.InvalidFileException: Invalid file

my file name :bazel-out/applebin_ios-ios_x86_64-dbg-ST-e481a8f1cc06/bin/Telegram/ShareInfoPlist.plist
this is my file 

[ShareInfoPlist(plist format).txt](https://github.com/MobileNativeFoundation/rules_xcodeproj/files/11335724/ShareInfoPlist.plist.format.txt)

### Reproduction steps

python3 build-system/Make/Make.py \
    --cacheDir="$HOME/telegram-bazel-cache" \
    generateProject \
    --configurationPath=build-system/template_minimal_development_configuration.json \
    --xcodeManagedCodesigning

https://github.com/TelegramMessenger/Telegram-iOS

### Expected behavior

generateProject in xcode 

### rules_xcodeproj version

7f600ddd7cb3ebc59c696a4639b84b93267c7b6e

### Xcode version

14.2

### Bazel version

6.1.1

### rules_apple version

488633f6fa04cbc9310079e368955b9863754e64

### rules_swift version

e01b8f76e7666ac254f1780b00de33c1296da8ff

### Additional information

apple_support 12fc37b370ff460c8712f16eb61a4d1f5abfc565

**Comment by brentleyjones** [comment]
I wasn't able to repro with the steps above, becausse I think `--xcodeManagedCodesigning` wouldn't cause `ShareInfoPlist` to be created (since extensions are disabled).

ByThat said, by modifying the BUILD files I was able to get a simulator version of `ShareExtension` to exist, and the project generated just fine. Attached it the plist in my output base. What I noticed between our versions is your has a lot of extra whitespace. Did you accidentally add that before uploading, or is it really that malformed?

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key>
    <string>en</string>
    <key>CFBundleIdentifier</key>
    <string>org.bf70ee1b5802dea2.Telegram.Share</string>
    <key>CFBundleName</key>
    <string>Telegram</string>
    <key>CFBundlePackageType</key>
    <string>XPC!</string>
    <key>NSExtension</key>
    <dict>
        <key>NSExtensionAttributes</key>
        <dict>
            <key>IntentsSupported</key>
            <array>
                <string>INSendMessageIntent</string>
            </array>
            <key>NSExtensionActivationRule</key>
            <string>SUBQUERY (
    extensionItems,
    $extensionItem,
    SUBQUERY (
        $extensionItem.attachments,
        $attachment,
        ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "public.file-url" ||
        ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "public.movie" ||
        ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "public.image" ||
        ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "public.url" ||
        ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "public.text" ||
        ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "public.audio" ||
        ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "public.data" ||
        ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "public.vcard" ||
        ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "com.apple.pkpass"
    ).@count == $extensionItem.attachments.@count
).@count &gt; 0</string>
        </dict>
        <key>NSExtensionPointIdentifier</key>
        <string>com.apple.share-services</string>
        <key>NSExtensionPrincipalClass</key>
        <string>ShareRootController</string>
    </dict>
    </dict>
</plist>
```

**Comment by jalalimehdi** [comment]
Thank you so much  for your time

In these lines are produced from the program
https://github.com/TelegramMessenger/Telegram-iOS/blob/master/Telegram/BUILD line 1194

**Comment by brentleyjones** [comment]
Thanks. But my attached file doesn't have extra whitespace at start of some of the lines. I assume you just copied the file incorrectly, but if you didn't, and that is how it is on disk, then that would be the issue (a malformed file that `plistlib.load` can't open). I can't reproduce the error though: the project generates just fine for me.

**Comment by jalalimehdi** [comment]
You said right
extra whitespace at start of some of the lines had caused my error
thanks
