### ISSUE TITLE
Bug: `Archive` on BwX

### ISSUE THREAD

**Issue by wendyliga** [MobileNativeFoundation/rules_xcodeproj#2152]
### Description

I am running the xcodebuild archive with this command
```
xcodebuild archive \    
-scheme Foo \
-configuration Release \
-destination 'generic/platform=iOS Simulator' \
-archivePath './build/Foo.framework-iphonesimulator.xcarchive' \
-project 'Foo.xcodeproj' \
SKIP_INSTALL=NO \
BUILD_LIBRARIES_FOR_DISTRIBUTION=YES
```

but got this error
```
❌ error: PIFCache (/Users/wendy.liga/Library/Developer/Xcode/DerivedData/Tokopedia-eqllfbxhdlqgxraxahrobzdfhfac/Build/Intermediates.noindex/ArchiveIntermediates/SharedUI/IntermediateBuildFilesPath/XCBuildData/PIFCache) doesn't exist. If you manually cleared Derived Data, you need to close and re-open the project for the PIFCache to be created again. Using the "Clean Build Folder" command instead (⇧ ⌘ K) won't trigger this error. If this error still happens after re-opening the project, please file a bug report here: https://github.com/buildbuddy-io/rules_xcodeproj/issues/new?template=bug.md
** ARCHIVE FAILED **
```

`xcodebuild build` is working flawlessly

### Reproduction steps

- generate project with BwX
- run 
```
```
xcodebuild archive \    
-scheme Foo \
-configuration Release \
-destination 'generic/platform=iOS Simulator' \
-archivePath './build/Foo.framework-iphonesimulator.xcarchive' \
-project 'Foo.xcodeproj' \
SKIP_INSTALL=NO \
BUILD_LIBRARIES_FOR_DISTRIBUTION=YES
```
```

### Expected behavior

to generate archive

### rules_xcodeproj version

1.3.1

### Xcode version

14.2.0

### Bazel version

5.3.0

### rules_apple version

1.1.3

### rules_swift version

1.6.0

### Additional information

I want to generate xcframework for distribution. I found that Bazel doesn't have the capabilities to generate a swift framework with `BUILD_LIBRARIES_FOR_DISTRIBUTION=YES`. so I tried it with rules_xcodeproj with BwX.

**Comment by brentleyjones** [comment]
Sorry, but the Archive action isn't supported with rules_xcodeproj. We expect distribution artifacts to be built with Bazel.

https://github.com/MobileNativeFoundation/rules_xcodeproj/blob/6b72c5edb5a46dde42fe0a8eeae9848c80d49bdc/docs/faq.md#does-the-archive-action-work

**Comment by wendyliga** [comment]
@brentleyjones agree, but actually, the use case on this issue is for building a pre-compiled framework. it should be more flexible compare to `xcachieve`.

but sure, thanks for the response.
