### ISSUE TITLE
Feature Request: The bug about regenerating xcodeproj and the feature request about project setting attributes

### ISSUE THREAD

**Issue by uiChuanqi** [MobileNativeFoundation/rules_xcodeproj#2167]
Hi, i have generated my SampleApp.xcodeproj successfully, and the project works well, but now i have another trouble.

My project has some dependent libraries, and has also generated corresponding schemes in project, but now when i regenerate the xcodeproj using the command "bazel run", all project setting will be rewritten. After adding the pbxproj and xcschemes into the git management, i also need to do lots of discarding change works to recovery the project settings.

There will comes out a lot of changes in the xcscheme file about the dependent library, just like below,What should i do with them ?
<img width="1622" alt="2023-05-10 1" src="https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/112925246/adb407c7-e5b6-4ebd-aa33-3a53736ad887">

In additional, do we have any method to do the project setting works conveniently when we generate the xcodeproj? 
"some method" , just like using xcconfig files. "the project setting works" are just like setting the "Build Setting"  attributes in the xcode, for example, the "Enale Bitcode", "Other linker flag", "Swift Language Version", and "Build Libraries for Distribution". 
<img width="890" alt="2023-05-10 2" src="https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/112925246/b9ed5ef4-3dd1-43c5-bd15-a9f4acba0e12">

Thanks a lot for reading this feature request, best regards, and looking forwards to your feedback.

**Comment by brentleyjones** [comment]
Hi!

A couple things:

- You shouldn't check in the generated project to version control. It will have absolute paths specific to each developer. Also, we won't guarantee that the generated projects and schemes won't be adjusted by Xcode for small formatting differences. (And a future rewrite might make this a lot worse.)
- You shouldn't adjust the generated project settings in Xcode. For the most part that won't change anything, as bazel is in control. You should adjust your BUILD files or `.bazlerc` file to adjust any build settings. You can learn how to do that by search for bazel questions related to what you are trying to adjust, asking in Bazel GitHub discussions, or asking in the Bazel slack.
- You shouldn't manually adjust or create schemes. rules_xcodeproj does some special stuff with them to make them work correctly. Use `xcodeproj.schemes` to define custom schemes and `xcodeproj.scheme_auto_generation_mode` to adjust how the automatic schemes are created.
