### ISSUE TITLE
Bug: The generation project encountered a duplicate target

### ISSUE THREAD

**Issue by Kila2** [MobileNativeFoundation/rules_xcodeproj#2210]
### Description

The generation project encountered a duplicate target, which corresponds to different configurations. Only `//command_line_option: apple_split_cpu` is different. I hope to optimize this duplicate target to avoid repeated compilation.

here is a deps graph example.
```
macos_command_line_applicationA
|-swift_libraryB
  |-swift_libraryA
macos_applicationA
|-swift_libraryC
  |-swift_libraryA
```

these target are set minimum_os_version to 11.0

I'm try custom rules_apple remove code about apple_split_cpu then generate project isn't contain duplicate target.

### Reproduction steps

See the Description

### Expected behavior

generate project don't contain duplicate target

### rules_xcodeproj version

1.5.1

### Xcode version

14.3

### Bazel version

6.2.0

### Additional information

RT

**Comment by thiagohmcruz** [comment]
If you could share a minimal repro it would be great 🙏

**Comment by Kila2** [comment]
> If you could share a minimal repro it would be great 🙏

I was make minimal repo at https://github.com/Kila2/rules_xcodeproj/tree/issues/2210/examples/integration
```
cd /path/to/integration
$bazel run //:xcodeproj
```
use bazel config to get d9fd065 and 4a69d99 configuration
```
$bazel cquery "deps(//macOSApp/LibB:LibB)"
//macOSApp/LibB:LibB (d9fd065)
//macOSApp/LibB:LibB (4a69d99)
//macOSApp/LibB:LibB (c80b949)
```
