### ISSUE TITLE
Bug: Not getting Cache hits when using rules_xcodeproj

### ISSUE THREAD

**Issue by sanju-naik** [MobileNativeFoundation/rules_xcodeproj#2222]
### Description

Cache hits are not working between CLI <> rules_xcodeproj builds. 

I invoked a Debug build from CLI  and it populates the Local Disk Cache, then when I invoke the same Debug build from Xcode UI [rules_xcodeproj], it rebuilds instead of using artifacts from Local Disk Cache.

The source files are the same between both builds, there might be differences in flags/options as rules_xcodproj has its own .bazelrc file, I tried passing almost all flags from rulesxcodeproj's `build:_rules_xcodeproj_build` flags in CLI invocation but still, the artifacts not reused, xcodeproj still rebuilds. 

### Reproduction steps

Clone this project - https://github.com/sanju-naik/bazel-demo-github 

Cd'into BazelDemo directory and run below command from CLI
`bazel build --config=Debug --ios_multi_cpus=sim_arm64 --xcode_version=14.2 BazelDemo`

This builds and populates Local Disk Cache.

Then generate Xcodeproject using this command `bazel run //:BazelDemo_gen` open `BazelDemo.xcodeproj` and build BazelDemo Scheme, you would notices `worker` invocation for Swift compile, it rebuilds instead of downloading from Disk Cache. 

### Expected behavior

When the build is run from Xcode UI, it should download everything from Disk Cache, shouldn't build anything a.k.a there shouldn't be any `worker` invocations

### rules_xcodeproj version

1.4.0

### Xcode version

14.2

### Bazel version

6.0.0

**Comment by BalestraPatrick** [comment]
This is expected. As noted in this section: https://github.com/MobileNativeFoundation/rules_xcodeproj/blob/main/docs/usage.md#command-line-api

> rules_xcodeproj builds targets in its own [output base](https://docs.bazel.build/versions/main/guide.html#choosing-the-output-base). It does this to ensure that the [analysis cache](https://sluongng.hashnode.dev/bazel-caching-explained-pt-2-bazel-in-memory-cache#heading-in-memory-caching) isn’t affected by other Bazel commands, including project generation itself. In addition, rules_xcodeproj sets one of the project’s [Bazel configs](https://github.com/MobileNativeFoundation/rules_xcodeproj/issues/2222#bazel-configs). Because of this, normal Bazel commands, such as bazel build or bazel clean, won’t be the same as what is performed in Xcode.

The solution is either to use the command-line API to perform builds outside of Xcode in the same output base, or warm-up the cache somewhere else (in CI for example) such that action results can be pulled from the remote cache instead.

**Comment by sanju-naik** [comment]
> rules_xcodeproj builds targets in its own [output base](https://docs.bazel.build/versions/main/guide.html#choosing-the-output-base).

Even though rules_xcodeproj has its own output base, the Disk cache location is same for both CLI and rules_xcodeproj invocations right, so when the build options/configs are the same from .bazelrc ideally it should reuse artifacts from cache? or no? 

> or warm-up the cache somewhere else (in CI for example) such that action results can be pulled from the remote cache instead.

Yeah, this is our use case actually, we want to schedule a job on CI to upload artifacts to Cache, then those should be reused on dev machines, Can you help me with an example of how to warm-up the Cache? Thanks.

**Comment by BalestraPatrick** [comment]
The `xcodeproj` also uses transitions, so the cache keys will different and a disk cache won't help. From the [docs](https://github.com/MobileNativeFoundation/rules_xcodeproj/blob/6638713313784d96b3688908dd744e16379e583a/docs/usage.md#build):
> To build targets the same way as rules_xcodeproj requires more than just using this API, because the xcodeproj rule applies a [configuration transition](https://bazel.build/extending/config#user-defined-transitions) to targets. That means that building targets by specifying their labels will build potentially different versions of those targets, and minimally versions that have different cache keys.

In the page I linked above you can see an [example](https://github.com/MobileNativeFoundation/rules_xcodeproj/blob/6638713313784d96b3688908dd744e16379e583a/docs/usage.md#--generator_output_groups) of how to warm-up the cache as well.

```
bazel run //:xcodeproj -- --generator_output_groups=all_targets build
```

**Comment by sanju-naik** [comment]
Using this 
> bazel run //:xcodeproj -- --generator_output_groups=all_targets build 

worked 👍 . Thank you. 

However, I am noticing 2 issues with my project:

- Project targets are built twice when I invoke above command from CLI, but the same thing doesn't happen when I build from Xcode UI

- When I use both disk and remote Cache, above API skips disk cache, and interacts with only the remote cache, how can I use both caches?

would appreciate any help on these, Thank you.

**Comment by brentleyjones** [comment]
> Project targets are built twice when I invoke above command from CLI, but the same thing doesn't happen when I build from Xcode UI

Device and simulator, right? You can adjust your `target_environments` to just be `simulator` when you call it on CI to only build that.

> When I use both disk and remote Cache, above API skips disk cache, and interacts with only the remote cache, how can I use both caches?

How are you using both? The command-line API will use the same `.bazelrc` stuff.

**Comment by sanju-naik** [comment]
> Device and simulator, right? You can adjust your target_environments to just be simulator when you call it on CI to only build that.

Yeah, this was building it twice because of the device & simulator, adjusting  `target_environments` works fine 👍 . 

Also for a project which has `target_environments` set to both sim & device and when I build for simulator from within Xcode fit still creates device output directories i.e `applebin_ios-ios_arm64-dbg-ST-**` but this directory is small in size, so seems like created because of some device-related configs during project generation? 

> How are you using both? The command-line API will use the same .bazelrc stuff. 

Yeah both disk cache and remote cache are specified in .bazelrc. This is actually working fine now, its uploading to both caches, seems like one time glitch maybe. 

Things are working fine, closing this issue. Thank you 👍

**Comment by sanju-naik** [comment]
Maybe one last thing I want to put here is - since we can't condition below command to build for a certain architecture 
`bazel run //:xcodeproj -- --generator_output_groups=all_targets build` [doing so causes cache invalidation], this means to produce caches for arm simulators we need to run cache warm-up job on M1 machines, is this how folks are using it?

**Comment by brentleyjones** [comment]
Yes, you'll want to run it on the types of machines the developers are using. Otherwise you can look at `examples/integration/BUILD` for how you can create two xcodeproj targets that would target both architectures.
