### ISSUE TITLE
Bug: some errors about changing the generated project Build Setting by Xcode.

### ISSUE THREAD

**Issue by uiChuanqi** [MobileNativeFoundation/rules_xcodeproj#2231]
### Description

Hi, i have generated my SampleApp.xcodeproj successfully, and the project works well, but if you change the attribute "Build libraries for distribution" from the defaut value "NO" to "YES" like below, 
<img width="881" alt="2023-05-23 14 39 14" src="https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/112925246/25c61318-4719-4690-b18d-b7610a77ca9f">

there will comes out an error, just like below image displays, if you change the value to NO and build then, this error will disappear.
<img width="978" alt="2023-05-23 14 39 48" src="https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/112925246/e36d0608-c6eb-47d8-b2af-5820b24c0b08">
 
I don't know why the generated project gives that error, it seems that the  file ".private.swiftinterface" should be created when generating project or at a building moment. 

i wrote a shell script to create this file at that path, its content codes just like this below, the "PROJECT_NAME" is xcode's universal define, the "TARGET_TEMP_DIR" is defined by the bazel in "User-Defined" in the "Build Setting":
<img width="698" alt="2023-05-22 17 16 02" src="https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/112925246/68515881-06b4-41d5-9300-40599000523d">

then added it to "Bundle Phrases" like this:
<img width="801" alt="2023-05-23 15 17 14" src="https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/112925246/07140220-f9ac-4e7d-9de4-31bdc9fa1211">
if you build(command+B) now, that error doesn't disappear, but if you build the second time, that error will disappear.

<img width="730" alt="2023-05-23 15 21 36" src="https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/112925246/a8a019a1-07e4-49bb-aab3-fda9d1019cfa">

As you know, the "Build Libraries for Distribution" is an important and commonly used attribute in Build Setting to deal the swift version problems, should i deal it like the top doing, or could you give me some suggesstion?   
 I'll look forwards to your feedback, best regards !

### Reproduction steps

My BUILD content like below:

load("@rules_xcodeproj//xcodeproj:defs.bzl","top_level_target","xcodeproj",)
load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")
load("@build_bazel_rules_apple//apple:ios.bzl", "ios_application")

swift_library(
    name = "SampleAppLibrary",
    srcs = glob(["*.swift"]) ,
    data = glob(["Assets.xcassets/**"]),
    deps = [
         
    ],
    visibility = ["//visibility:public"],
)

xcodeproj(
    name = "xcodeproj",
    build_mode = "bazel",
    project_name = "SampleApp",
    tags = ["manual"],
    top_level_targets = [
          ":SampleApp",
    ],
    visibility = ["//visibility:public"],
)

ios_application(
    name = "SampleApp",
    bundle_id = "com.ui.SampleApp",
    families = ["iphone", "ipad"],
    minimum_os_version = "15.0",
    infoplists = [":Info.plist"],
    deps = [":SampleAppLibrary"],
    visibility = ["//visibility:public"],
)

1. open the terminal, cd to the SampleApp , Build and generate the project by bazel
bazel build //SampleApp:SampleApp
bazel run //SampleApp:xcodeproj  

2. change the attribute "Build libraries for distribution" from the defaut value "NO" to "YES", that error will come out.

### Expected behavior

the "Build Libraries for Distribution" is an important and commonly used attribute in Build Setting to deal the swift version problems, it should can be changed to YES

### rules_xcodeproj version

1.3.3

### Xcode version

14.2

### Bazel version

6.2.0

### rules_apple version

2.1.0

### rules_swift version

1.6.0

**Comment by brentleyjones** [comment]
Manually changing build settings it's supported. You will need to change something on the Bazel side (`BUILD` files and the like) to get the change you want. Also, most changes won't be reflected in build settings, as we use `OTHER_SWIFT_FLAGS`, with a params file, to specify most compiler flags).

That said, we probably don't support `--features=swift.supports_library_evolution` (the change you would need) in BwX mode (though it might work in BwB mode). If that flag doesn't work, please file a new bug.

**Comment by brentleyjones** [comment]
You'll want to put that flag in your `.bazelrc` file. Then you'll want to make sure that a normal bazel build, outside of Xcode, does what you want. Finally you can regen the project, which should apply the proper compiler flags for you.

**Comment by uiChuanqi** [comment]
I tried to set my .bazelrc like this,
![2023-05-25 19 32 29](https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/112925246/cc6c1783-0162-49d1-aa08-9ec259e8defe)

but it came out this error,
<img width="876" alt="2023-05-25 19 33 40" src="https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/112925246/63852007-a68d-4efc-bf29-37d737663658">




>

**Comment by brentleyjones** [comment]
The flag you need to set is `--features=swift.supports_library_evolution`.
