### ISSUE TITLE
Feature Request: how to use the variables difined in User-Defined in Build Setting

### ISSUE THREAD

**Issue by uiChuanqi** [MobileNativeFoundation/rules_xcodeproj#2266]
Hi,

I have successfully generated my project and i find that there are many variables defined by bazel under the "User-Defined" in the target's "Build Setting" like below, some of them are very useful for me, but i cannot use them directly. Could you give some suggestions about it ? Thank you.
![2023-06-01 11 41](https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/112925246/d0bbae35-474c-4b05-9569-cb5287337ab4)

**Comment by BalestraPatrick** [comment]
Where do you want to access these settings from? We have various scripts that already access them directly from the environment in certain run script phases: https://github.com/MobileNativeFoundation/rules_xcodeproj/blob/4dff71b4838d4ac800fca58d8b7fd1b4410e0d92/xcodeproj/internal/templates/bazel_build.sh#LL55C15-L55C36

**Comment by uiChuanqi** [comment]
> 

thank you for your reply, i am a new ios developer using swift, i want to access these variables when programming. Hmm..Emm, just like using the variables defined in the info.plist like this:

` let url = Bundle.main.infoDictionary?["Host_URL"] as! String`

**Comment by uiChuanqi** [comment]
> Where do you want to access these settings from? We have various scripts that already access them directly from the environment in certain run script phases: https://github.com/MobileNativeFoundation/rules_xcodeproj/blob/4dff71b4838d4ac800fca58d8b7fd1b4410e0d92/xcodeproj/internal/templates/bazel_build.sh#LL55C15-L55C36

Excuse me, i have tried to use those variables like below, 

```
project_path="${BAZEL_WORKSPACE_ROOT}"
mkdir -p "${project_path}/filterFiles"
```

but there comes out one error: 
"mkdir: /filterFiles: Read-only file system".
It seems that the "project_path" doesn't work, could you give me some suggesstions ?
