### ISSUE TITLE
Bug: ENABLE_TESTING_SEARCH_PATHS not set for BwX projects with 1.7.0

### ISSUE THREAD

**Issue by erikkerber** [MobileNativeFoundation/rules_xcodeproj#2285]
### Description

Generating projects with non-test targets that use `testonly = True` no longer have `ENABLE_TESTING_SEARCH_PATHS` applied.

### Reproduction steps

1. Create a lib that leverages XCTest but is not a test target
2. Set `testonly = True`
3. Build with BwX

### Expected behavior

`ENABLE_TESTING_SEARCH_PATHS` is set for these targets

### rules_xcodeproj version

1.7.0

### Xcode version

14.3.1

### Bazel version

6.2

**Comment by brentleyjones** [comment]
We pass through the framework and include search paths, so we shouldn’t need this build setting anymore. If it can build with bazel it should be able to build currently. What are the missing arguments?

**Comment by erikkerber** [comment]
`Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.4.sdk/Developer/Library/Frameworks` is missing

For this target I don't see a params file passed. Is that expected in BwX?

**Comment by brentleyjones** [comment]
All modes should have a params file passed. Should be set in `OTHER_SWIFT_FLAGS`.

**Comment by brentleyjones** [comment]
This is a bug with the `-I` filtering. I'll get a fix this morning. It's filtering out `-I /Applications/Xcode.app/Contents/Developer/Platforms/$PLATFORM/Developer/usr/lib` incorrectly in BwX mode.
