### ISSUE TITLE
Bug: Unable to find the `Key` for the `TargetID` when top_level_targets contain targets generated by same macro in same package

### ISSUE THREAD

**Issue by David-Lam** [MobileNativeFoundation/rules_xcodeproj#2289]
### Description

We were upgrading our project to use 1.7.0 but hit the following error:
```
Unable to find the `Key` for the `TargetID`, "//MyPackage:MyTests.__internal__.__test_bundle applebin_ios-ios_x86_64-dbg-ST-4abc478c7114". (function: init(referencedContainer:targets:targetHosts:extensionPointIdentifiers:consolidatedTargetKeys:pbxTargets:), file: tools/generators/legacy/src/Generator/TargetResolver.swift, line: 51)
```

I did some digging and found that the regression is introduced by [Fix tests in custom scheme when ios_unit_test.bundle_name is used](https://github.com/MobileNativeFoundation/rules_xcodeproj/commit/f335ff2dd12c3ce71f32d20920a4e5c427a04efa) . This [change](https://github.com/MobileNativeFoundation/rules_xcodeproj/commit/f335ff2dd12c3ce71f32d20920a4e5c427a04efa#diff-31ddaae3d278246b432650a6d8c1b1a4e6940ce58ae5df7fae0c16fb00ebf758R290-R293) switch to using `generator_name` to construct target replacement label. However, some of our test targets are expanded under the same macro (have same `generator_name`), which cause those targets to have identical target replacement label. This cause the error to be thrown when we generate project that contains multiple test targets with same `generator_name` and package in `top_level_targets`.

### Reproduction steps

See repro diff at https://github.com/David-Lam/rules_xcodeproj/pull/1/files.

Checkout [dlam-reproKeyError](https://github.com/David-Lam/rules_xcodeproj/tree/dlam-reproKeyError) at https://github.com/David-Lam/rules_xcodeproj then run:
```
cd examples/rules_ios/
bazel run //:xcodeproj
```

### Expected behavior

`bazel run //:xcodeproj` should complete successfully. 

### rules_xcodeproj version

1.7.0

### Xcode version

14.1

### Bazel version

6.2.0

**Comment by thiagohmcruz** [comment]
Repro is good, I can hit the issue and will investigate, def an edge case I missed while implementing this. Thx @David-Lam!
