### ISSUE TITLE
Bug: Configurable attributes not working with custom flags

### ISSUE THREAD

**Issue by louwers** [MobileNativeFoundation/rules_xcodeproj#2302]
### Description

We're trying to use `rules_xcodeproj` with configurable attributes and [custom flags](https://bazel.build/docs/configurable-attributes#custom-flags).

However when passing our custom flag

```
bazel run //:xcodeproj --//:word=2
```

The wrong value for `select()` is chosen.

### Reproduction steps

Reproduction: https://github.com/louwers/reproduction-xcodeproj

```bzl
load("@bazel_skylib//rules:common_settings.bzl", "string_flag")
load(
    "@rules_xcodeproj//xcodeproj:defs.bzl",
    "xcodeproj",
)

string_flag(
    name = "word",
    values = ["1", "2"],
    build_setting_default = "1",
)

config_setting(
  name = "word1",
  flag_values = {
    "word": "1"
  }
)

config_setting(
  name = "word2",
  flag_values = {
    "word": "2"
  }
)

cc_binary(
  name = "example",
  srcs = [
    "main.cc",
    "word.h"
  ] + select({
    "word1": ["word1.cc"],
    "word2": ["word2.cc"]
  }),
  visibility = ["//visibility:public"],
)

xcodeproj(
    name = "xcodeproj",
    project_name = "ExampleProj",
    tags = ["manual"],
    top_level_targets = [
        "example"
    ],
)
```

Run:

```sh
bazel run //:xcodeproj --//:word=1  # prints hello
bazel run //:xcodeproj --//:word=2  # prints world

bazel run //:xcodeproj --//:word=2
# will print hello and includes word1.cc instead of word2.cc
xed ExampleProj.xcodeproj
```

### Expected behavior

I expect `word2.cc` to be included in the Xcode project in the above example when running

```
bazel run //:xcodeproj --//:word=2
```

### rules_xcodeproj version

1.7.1

### Xcode version

14.3

### Bazel version

6.2.1

**Comment by brentleyjones** [comment]
We don't support passing flags that way. You need to set it in your .bazelrc/xcodeproj.bazelrc file(s), or use [extra config flags](https://github.com/MobileNativeFoundation/rules_xcodeproj/blob/main/docs/usage.md#extra-config-flags).

**Comment by louwers** [comment]
Alright, we thought so already. :)

Could you give an example of how to use the extra config flags?

**Comment by louwers** [comment]
Ah, like this:

```
bazel run //:xcodeproj --@rules_xcodeproj//xcodeproj:extra_common_flags="--//:word=2"
```

It wasn't clear to me if I needed to pass a file or something else. But now I get it.

Thanks!
