### ISSUE TITLE
Bug: `ios_unit_test` with multiple `deps` not working

### ISSUE THREAD

**Issue by louwers** [MobileNativeFoundation/rules_xcodeproj#2330]
### Description

When I have a `ios_unit_test` with one `objc_library` in `deps`, everything is fine. The tests show up on Xcode under the target:

<img width="272" alt="image" src="https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/649392/3c79cd8f-6c27-4217-8705-f8f5e86bfc80">

However, when I add another target to `deps`, it fails. 0 tests are shown.

<img width="263" alt="image" src="https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/649392/74e1e6f0-1de4-4791-bd70-97090cd9e48b">

It doesn't matter if the targets are from the same package or not.

### Reproduction steps

https://github.com/louwers/repro-xcodeproj-ios-unit-test

```
bazel run xcodeproj
xed MapLibre.xcodeproj
```

Open tests tab in Xcode left sidebar.

### Expected behavior

Test targets are combined like below:

<img width="160" alt="image" src="https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/649392/978566a3-b9ac-47f5-bc38-4d2250391421">

### rules_xcodeproj version

1.7.1

### Xcode version

14.3

### Bazel version

6.2.1

**Comment by brentleyjones** [comment]
`ios_unit_test` is a bundling rule. It should have a single dep that represents the main module. You can have multiple deps, but then target merging (which causes the code and the bundling to become one target in Xcode) to not work.

**Comment by louwers** [comment]
OK, I found out that  that after I click 'run' in Xcode they all start showing up like expected!

So I guess Xcode needs to discover what tests exist before it can show them.

Don't know why this works with a single target but not with multiple (or even with a single `deps` after I combine all targets in a single `objc_library`).

**Comment by brentleyjones** [comment]
It works with a single target because all of the sources for that target get associated with the test bundle. And because of that Xcode can correctly index them, showing the tests ahead of time. When there are multiple targets, then those sources are associated with static library targets, and the test bundle has a "compile stub". In that case Xcode doesn't know that those tests exist until after they run.
