### ISSUE TITLE
Feature Request: Support visionOS

### ISSUE THREAD

**Issue by brentleyjones** [MobileNativeFoundation/rules_xcodeproj#2352]
https://github.com/bazelbuild/rules_apple/issues/2012

**Comment by brentleyjones** [comment]
@erikkerber @BalestraPatrick Anything we need to do in rules_xcodeproj for this? I assume minimally we need to adjust `platforms.bzl` to include the new platforms?

**Comment by BalestraPatrick** [comment]
@brentleyjones I can take a look at this.
