### ISSUE TITLE
Bug: Xcode 15 error: Could not parse libtool version from:

### ISSUE THREAD

**Issue by narlei** [MobileNativeFoundation/rules_xcodeproj#2353]
### Description

Hey all! I have been testing the rules_xcodeproj with Xcode 15 Beta (all versions). I'm receiving an error message when trying to build a Scheme.
"Could not parse libtool version from:"
![Screenshot 2023-07-12 at 15 13 23](https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/8092922/4f15eea4-93e8-438b-b127-7ad2fd544dbe)

I can reproduce the error only when I'm building a Scheme with a launch app, including the app and the related libraries on the focused_targets. Our schemes are generated as custom (using `xcode_schemes.scheme(` to define our schemes).

I tested using the last rules_xcodeproj version (1.7.1) and using the last commit too (https://github.com/MobileNativeFoundation/rules_xcodeproj/commit/d1f9dacf28a9ba6c09f5600502e7a733f7e71c54).

When I call libtool on my terminal it works perfectly, I think the error may be related to some libtool wrapper.
 

### Reproduction steps

 I'm working with custom schemes, when I create a custom scheme and focus on it, the error occurs:

```
SCHEMES = [
    xcode_schemes.scheme(
        name = "MyApp",
        build_action = xcode_schemes.build_action(
            targets = [
                "//MyApp:Library",
            ],
        ),
        launch_action = xcode_schemes.launch_action(
            "//MyApp:MainApp",
        ),
    ),
]

XCODEPROJ_FOCUSED_TARGETS = [
            "//MyApp:Library"
            "//MyApp:MainApp",
]

xcodeproj(
    ...
    focused_targets = XCODEPROJ_FOCUSED_TARGETS,
    schemes = SCHEMES,
    ...
)
```

### Expected behavior

Build the project without errors.

### rules_xcodeproj version

1.7.1

### Xcode version

Version 15.0 beta 4 (15A5195m)

### Bazel version

6.1.1 - 6.2.1

### rules_apple version

2.2.0

### rules_swift version

1.7.1

**Comment by brentleyjones** [comment]
@chiragramani this seems similar to the `SWIFT_EXEC` thing we had to solve for Xcode 15. Mind taking a look?

**Comment by brentleyjones** [comment]
I have a fix coming.
