### ISSUE TITLE
Bug: Target was not found in the transitive dependencies of top_level_targets attribute.

### ISSUE THREAD

**Issue by andre-alves** [MobileNativeFoundation/rules_xcodeproj#2402]
### Description

Given this (simplified) sample:

```python
# BazelSample/BUILD.bazel
xcodeproj(
    name = "BazelSampleXcodeProj",
    build_mode = "bazel",
    focused_targets = [
        ":BazelSampleApp",
        ":BazelSample",
    ],
    project_name = "BazelSample",
    schemes = [
        xcode_schemes.scheme(
            name = "CustomScheme",
            build_action = xcode_schemes.build_action(
                targets = [
                    ":BazelSample",
                ],
            ),
            launch_action = xcode_schemes.launch_action(
                ":BazelSampleApp",
            ),
        ),
    ],
    top_level_targets = [":BazelSampleApp"],
)

ios_application(
    name = "BazelSampleApp",
    deps = [":BazelSample"],
)

swift_library(
    name = "BazelSample",
    srcs = glob(["Main/Sources/**/*.swift"]),
    module_name = "BazelSample",
)
```

```
bazel run //BazelSample:BazelSampleXcodeProj
...
ERROR: Internal precondition failure:
Target @//BazelSample:BazelSample was not found in the transitive dependencies of @//BazelSample:BazelSampleXcodeProj's `top_level_targets` attribute. Did you reference an alias (only actual target labels are supported in Scheme definitions)? Check that @//BazelSample:BazelSample is spelled correctly, and if it is, add it or a target that depends on it to @//BazelSample:BazelSampleXcodeProj's `top_level_targets` attribute.
```

This error is surprising because `BazelSampleApp` is present in `top_level_targets` and has a dependency on `BazelSample`.

Is the error expected in this case?

### Reproduction steps

Check this repro: https://github.com/andre-alves/xcodeproj_top_level_repro/tree/main

`bazel run //BazelSample:BazelSampleXcodeProj`

### Expected behavior

Generate the project successfully.

### rules_xcodeproj version

1.8.1

### Xcode version

14.1

### Bazel version

6.2.1

### rules_apple version

2.5.0

### rules_swift version

1.9.1

**Comment by thiagohmcruz** [comment]
@brentleyjones remind me, is it expected to be able to set non-"top level targets" in Custom Schemes? 

I verified [here](https://github.com/MobileNativeFoundation/rules_xcodeproj/blob/main/xcodeproj/internal/xcodeproj_rule.bzl#L524C9-L524C79) that the `swift_library`'s `merge.src.id` is set to the `ios_application`'s key `merge.dest`. I assume that means it will be piped through the target merging logic. Is this expected?

**Comment by brentleyjones** [comment]
Yes, non-top level targets are allowed, they just have to be a transitive dependency of a top-level target.

And you are correct, this is an interesting target merging bug. Seems we need to check a target's `compileTargets\.ids` in the scheme logic.

**Comment by brentleyjones** [comment]
@andre-alves for now, just leave off the `build_action`, it's not needed.

**Comment by thiagohmcruz** [comment]
Cool thx @brentleyjones!

We can repro too using our integration examples btw, just added a new custom scheme [here](https://github.com/MobileNativeFoundation/rules_xcodeproj/blob/main/examples/integration/xcodeproj_targets.bzl#L127) using `"//iOSApp/Source:iOSApp"` in `launch_action` and `"//iOSApp/Source:iOSApp.library"` in `build_action`.

What is weird is that other `swift_library` targets are picked up correctly and don't error out, e.g. [MixedAnswerLib_Swift](https://github.com/MobileNativeFoundation/rules_xcodeproj/blob/main/examples/integration/iOSApp/Source/CoreUtilsMixed/MixedAnswer/BUILD#L43).

**Comment by andre-alves** [comment]
Incremental generator fixed this issue 👍
