### ISSUE TITLE
Bug: Xcode target icons don't match target types

### ISSUE THREAD

**Issue by luispadron** [MobileNativeFoundation/rules_xcodeproj#2486]
### Description

In Xcode I'd expect to see the icon of the app when selecting / viewing it's target in the scheme selector

Instead we see something like:

<img width="68" alt="Screenshot 2023-08-21 at 11 43 36 AM" src="https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/13840545/c3f01c14-c8e5-40f2-9539-3bf4a7a5b9cd">

### Reproduction steps

1. rules_ios example
2. Select app target, notice generic icon and not app icon

### Expected behavior

The apps icon is displayed for the target.

### rules_xcodeproj version

1.9.1

### Xcode version

14.2.1

### Bazel version

6.3.0

### Additional information

Possibly broken in: https://github.com/MobileNativeFoundation/rules_xcodeproj/pull/2407

**Comment by brentleyjones** [comment]
The icon comes after the Info.plist is generated, based on the `info_plists.adjust_for_xcode` code. Did you fully verify behavior from before 1.9.0 and after?

**Comment by luispadron** [comment]
No I haven't tbf, working on adding an example to rules_ios which exercises this. It's working in `1.8.1` though which is what we're currently on

**Comment by luispadron** [comment]
Weird 1.8.1 `examples/rules_ios` doesn't have the app icon in the schemes selector but i do see it show up in our real project using that version

**Comment by brentleyjones** [comment]
You have to build once for the Info.plist to be generated. Then you have to close and open the Xcode project to have Xcode refresh (iirc).

**Comment by luispadron** [comment]
Ah yep the build is required, luckily closing is not. If I checkout 1.8.1, generate rules_ios example and build it shows up after some seconds.

**Comment by luispadron** [comment]
Closing this, not an issue. Tested in our project using 1.9.1 and after building the target + closing/opening Xcode the icon shows up.
