### ISSUE TITLE
Bug: Unable to run ui tests on real device

### ISSUE THREAD

**Issue by mikhailmulyar** [MobileNativeFoundation/rules_xcodeproj#2539]
### Description

UI Tests target not allows to select real device as destination.

### Reproduction steps

Add ui tests target with provisioning profile set.
```
 ios_ui_test(
    name = "MyTestTarget",
    minimum_os_version = minimum_os_version,
    provisioning_profile = "provisions/MyTestTarget.mobileprovision",
    test_host = "//:MyTarget",
    deps = [
        "//MyTests",
    ],
)
```
Generate project
When trying to select device as destination it doesn't show connected device as eligible destination.

### Expected behavior

Xcode allows to select real device as destination for ui tests target.

### rules_xcodeproj version

1.10.0

### Xcode version

14.3.1

### Bazel version

6.1.0

### rules_apple version

2.5.0

### rules_swift version

1.9.1

**Comment by ken4ward** [comment]
Were yuo able to run it on a simulator?

**Comment by brentleyjones** [comment]
By default only the simulator target environment is set. You will need to do something like this:

```starlark
xcodeproj(
    ...
    top_level_targets = [
        ...
        top_level_targets(
                labels = [
                    "//:MyTestTarget",
                ],
                target_environments = ["device", "simulator"],
        ),
        ...
)
```

I just tested this and was able to run the UI tests on device or simulator.

**Comment by mikhailmulyar** [comment]
Thanks. It works, the only downside that I have to select provisioning profile by myself in Xcode. It is not picking up profile from build file

**Comment by brentleyjones** [comment]
It should pick it up. If you have a repro, we can look at it.
