### ISSUE TITLE
Bug: `swift_test` plugin dependency `.swiftmodule`s are not generated during Index Build

### ISSUE THREAD

**Issue by chiragramani** [MobileNativeFoundation/rules_xcodeproj#2563]
### Description

Target builds and runs all great, which is really cool. I saw an indexing issue when exploring rules_swift examples:
<img width="663" alt="Screenshot 2023-09-08 at 10 58 07 AM" src="https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/11925399/6c69dea0-1a67-48b2-af1c-f4f013c639c0">

I see that the indexing invocations `-I` dirs don't have `StringifyMacroPlugin.swiftmodule`. When I modify the project by explicitly adding an -I pointing to a directory that has`StringifyMacroPlugin.swiftmodule`, indexing is all green.

### Reproduction steps

1. rules-swift 1.11 release.
2. Generate a rules_xcodeproj that has top-level targets: "stringify_macro", "stringify_client", "stringify_macro_test"
3. In the generated BwB project, go to StringifyMacroTests.swift.
4. Build the project. 
5. Project builds all great leaving an indexing issue to be fixed.

### Expected behavior

Indexing ✅

### rules_xcodeproj version

858c3967d4e2c7f8997e585769639da9ce4742f4

### Xcode version

Xcode 15 Beta 8 (15A5229m)

### Bazel version

6.2.0

### rules_swift version

1.11

**Comment by brentleyjones** [comment]
I'll look at this Monday.
