### ISSUE TITLE
Bug: rules_ios apple_framework does not support SwiftUI Previews in rules_xcodeproj

### ISSUE THREAD

**Issue by m-petes** [MobileNativeFoundation/rules_xcodeproj#2612]
### Description

SwiftUI Previews do not work for `rules_ios` `apple_framework` targets in `rules_xcodeproj`. This can be seen in the existing `rules_ios` example in the repo by using the `ContentView.swift` file in the `UI` module.

By default, the swift files in the `apple_framework` target only show as included for the static library target created by `rules_ios`, not the framework target. This prevents the preview from working since it needs to be a part of the framework target.

![Screenshot 2023-09-20 at 9 02 07 AM](https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/112505859/b42540ca-7bd5-4c70-a583-45725fb5b25c)
![Screenshot 2023-09-20 at 9 03 07 AM](https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/112505859/afb04b20-b294-4ed1-98dd-c752cdbddde5)

If I manually add the the SwiftUI preview file to the framework target and select that framework as the current scheme in my xcodeproj, I receive an error.

![Screenshot 2023-09-20 at 9 03 56 AM](https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/112505859/61eac576-3e3e-49a2-8eb8-a285b4e3f33e)
![Screenshot 2023-09-20 at 9 10 51 AM](https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/112505859/8b012beb-1536-4cdb-968c-3ab7fe9f036e)
```
HumanReadableSwiftError

ProviderError: ProviderError: noPreviewInfos(runDestination: Simulator - iOS 16.2 | iphonesimulator | arm64 | iPhone 14 Pro Max | no proxy, thunkConfiguration: <IDEBuildOperationConfiguration buildCommand: 8, buildParameters: <IDEBuildParameters:0x6000a024f3e0:action=build:command=<IDEConcretePrimitiveSchemeCommand:0x600003338150:Run>:config=Debug:dest=iPhone 14 Pro Max:arch=arm64:workspaceArena=<IDEWorkspaceArenaSnapshot: 0x600000859e30>:
overridingProperties=(
{ // Preview overrides (immutable)
   DSTROOT = 【𝗟𝗶𝘁𝗲𝗿𝗮𝗹𝗦𝘁𝗿𝗶𝗻𝗴:/Users/michaelpeterson/Dev/rules_xcodeproj/examples/rules_ios/DerivedData/rules_ios/Build/Intermediates.noindex/Previews/UI (Static Framework)/ReleaseProducts】
   ENABLE_PREVIEWS = 【YES】
   OBJROOT = 【𝗟𝗶𝘁𝗲𝗿𝗮𝗹𝗦𝘁𝗿𝗶𝗻𝗴:/Users/michaelpeterson/Dev/rules_xcodeproj/examples/rules_ios/DerivedData/rules_ios/Build/Intermediates.noindex/Previews/UI (Static Framework)/Intermediates.noindex】
   SYMROOT = 【𝗟𝗶𝘁𝗲𝗿𝗮𝗹𝗦𝘁𝗿𝗶𝗻𝗴:/Users/michaelpeterson/Dev/rules_xcodeproj/examples/rules_ios/DerivedData/rules_ios/Build/Intermediates.noindex/Previews/UI (Static Framework)/Products】
},
):
collectBuildTimeStatistics=NO
collectTimelineMetrics=NO>, executionEnvironment: Optional(<IDEExecutionEnvironment: 0x123b7b860>), singleFileToBuild: nil, buildLog: nil, parallelizeBuildables: true, dontActuallyRunCommands: false, buildImplicitDependencies: false, skipDependencies: false, buildables: Optional([<Xcode3TargetProduct:0x60000064e8e0:UI. blueprint:<Xcode3Target:0x1553a6660:UI (Static Framework)>>]), subsetOfBuildables: nil, buildDescriptionID: nil, scheme: Optional(<IDEScheme:0x15539b100:'UI (Static Framework)'>), schemeTask: 0, clientInfo: nil>, blueprintName: UI (Static Framework), sourceFilePath: /Users/michaelpeterson/Dev/rules_xcodeproj/examples/rules_ios/UI/ContentView.swift, thunkVariantSuffix: __XCPREVIEW_THUNKSUFFIX__)
```

I also tried adding `link_dynamic = True` to the UI `apple_framework` target and resolving the Info.plist issues that came with that, but I still received the same error.

Thanks so much!

### Reproduction steps

You can use the `rules_ios` example in this repo with the `ContentView.swift` SwiftUI preview in the UI module, and follow the steps I tried above to see the outputs.

### Expected behavior

It would be awesome if SwiftUI Previews were supported with minimal configuration needed in `rules_ios` `apple_framework` targets that are used in `rules_xcodeproj`.

### rules_xcodeproj version

1.9.1

### Xcode version

14.2

### Bazel version

6.2.1

**Comment by thiagohmcruz** [comment]
@m-petes this is working in the [Incremental generation mode](https://github.com/MobileNativeFoundation/rules_xcodeproj/issues/2701) which is going to be the default. In the epic there are instructions on how to test it, it would be great if you could help us verify it's fixed there for you too.

This is the diff to enable it leveraging `link_dynamic` (`bundle_id` is required by `rules_ios` when linking dynamically):
```sh
diff --git a/examples/rules_ios/UI/BUILD b/examples/rules_ios/UI/BUILD
index 9e387dcf..e791f5c5 100644
--- a/examples/rules_ios/UI/BUILD
+++ b/examples/rules_ios/UI/BUILD
@@ -8,6 +8,8 @@ rules_ios_apple_framework(
     srcs = glob(["*.swift"]),
     infoplists = ["Info.plist"],
     module_name = "UI",
+    link_dynamic = True,
+    bundle_id = "com.foo.ui",
     platforms = {
         "ios": "15.0",
     },
```

<img width="1485" alt="Screenshot 2023-11-29 at 4 27 00 PM" src="https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/10197663/3ff4d506-06cc-4721-9896-5faf3921202c">

cc @brentleyjones worth trying to find a fix in the legacy one? IMO even if we find one it's likely to be short lived?

**Comment by brentleyjones** [comment]
I don't think it's worth trying to fix in legacy generation mode. I believe numerous fixes in incremental generation mode combined results in this working.

**Comment by m-petes** [comment]
Yep, fixed in incremental generation mode! :D Thank you so much!
