### ISSUE TITLE
Bug: Broken Xcode previews with rules_apple 3.0.0

### ISSUE THREAD

**Issue by gferon** [MobileNativeFoundation/rules_xcodeproj#2640]
### Description

I tried living on the edge and updated `rules_apple` to v3.0 but Xcode Previews stopped working. The `xcodeproj` has a top_level_target with a single `ios_framework` which depends on a few dozen other smaller `ios_framework` (which in turn depend on a single `swift_library`). This works with `rules_apple` v2.5.

### Reproduction steps

- Try Xcode previews with `rules_apple` v3
- Witness error **"Cannot preview in this file" - "Active scheme does not build this file"**

### Expected behavior

Xcode Preview should build and run for a single `ios_framework`.

### rules_xcodeproj version

1.11.0

### Xcode version

15.0

### Bazel version

6.3.0

### rules_apple version

3.0.0

### rules_swift version

1.12.0

**Comment by brentleyjones** [comment]
Which scheme do you have selected (one for the framework or a target that depends on the framework)? Do you have the same project open in multiple Xcodes?

I ask all of this, because I can't repro in `examples/integration`, which is using rules_xcodeproj 3.0.0. (I do get a different dylib error that I'm now looking into though.)

**Comment by gferon** [comment]
> Which scheme do you have selected (one for the framework or a target that depends on the framework)? Do you have the same project open in multiple Xcodes?

The selected scheme is indeed the one for the framework. Let me try to see if there's any obvious difference in the scheme between both `rules_apple` versions.

**Comment by brentleyjones** [comment]
The bug I encountered is specific to `--define=apple.experimental.tree_artifact_outputs=0` (which I'm working on a fix for).

**Comment by gferon** [comment]
Do you know if that's something that was flipped in `rules_apple` v3? We don't use that flag.

**Comment by gferon** [comment]
So, this is the source files associated to the framework scheme with both `rules_apple` versions. Could you point me to the place where we collect those in `rules_xcodeproj`? I can add a few `print` and try to understand what's going on.

![Screenshot from 2023-09-29 15-49-05](https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/420581/81a64053-213a-414d-9e32-e429793e4159)

![Screenshot from 2023-09-29 15-51-40](https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/420581/c418e05c-c848-4a20-88e4-879e29caffe0)

**Comment by brentleyjones** [comment]
> I wonder what changed in rules_apple though.

If you can create a repro, that would be great. We strive to have target merging work, and this seems like a regression.

**Comment by gferon** [comment]
> If you can create a repro, that would be great. We strive to have target merging work, and this seems like a regression.

I'll give it a shot.

Could you also point me to the place where we collect those source files from (maybe) transitive dependencies of a Bazel target?

**Comment by brentleyjones** [comment]
That's not what matters here, it's the target merging logic. It's currently a little gnarly (and is being improved in a rewrite), but it starts with `potential_target_merges`: https://github.com/MobileNativeFoundation/rules_xcodeproj/blob/9a07ba68c213455936e59bced3872be441f5fd6e/xcodeproj/internal/xcodeproj_rule.bzl#L506-L508
