### ISSUE TITLE
`cc_library` depending on header generated with genrule not regenerating

### ISSUE THREAD

**Issue by louwers** [MobileNativeFoundation/rules_xcodeproj#2691]
Reproduction here:

https://github.com/louwers/bug-cc-library-generated-header-rules-xcodeproj

Just run.

```
git clone git@github.com:louwers/bug-cc-library-generated-header-rules-xcodeproj.git

bazel run //:xcodeproj

bazel build //:lib  # all good

xed Repro.xcodeproj

# run lib target in Xcode

# uncomment first line of gen_header.sh

bazel build //:lib  # now fails due to static_assert(false)

# run lib target in Xcode
# still works, even with static_assert(false); now in the header!
```

We have the same problem with an `ios_application` depending on a `cc_library` like this. But I could not reproduce it with the `cc_binary`.

**Comment by louwers** [comment]
I forgot to add the Bazel files to the repro.

They are added now.

**Comment by louwers** [comment]
Let me know if I should try making a reproduction with the app as well. The full dependency chain is:

`genrule` <- `cc_library` (header only) <- `cc_library` <- `objc_library` <- `objc_library` <- `ios_application`

**Comment by mwilsnd** [comment]
Is there a way to clear whatever cache is stuck to work around this in the short term? Cleaning the bazel project doesn't appear to be enough.

**Comment by brentleyjones** [comment]
I was traveling for BazelCon. I can probably look at this tomorrow sometime. But maybe I won't get to it until Friday.

**Comment by louwers** [comment]
Have fun @brentleyjones :)

**Comment by brentleyjones** [comment]
And OOO today, I'll look Monday.
