### ISSUE TITLE
Bug: @bazel_features_globals is not defined

### ISSUE THREAD

**Issue by imooccodejesse** [MobileNativeFoundation/rules_xcodeproj#2692]
### Description

rules_xcodeproj/xcodeproj/internal/xcodeproj_rule.bzl:3:6: at /private/var/tmp/_bazel_jesse/53421a33a08e756b1acd93ad0a40cdee/rules_xcodeproj.noindex/build_output_base/external/bazel_features/features.bzl:3:6: Unable to find package for @bazel_features_globals//:globals.bzl: The repository '@bazel_features_globals' could not be resolved: Repository '@bazel_features_globals' is not defined.

### Reproduction steps

bazel run //DemoProject:Demo-GeneratedProject

### Expected behavior

Demo-GeneratedProject.xcodeproj file is successfully generated

### rules_xcodeproj version

1.12.1

### Xcode version

15.0.1

### Bazel version

6.2.1

### rules_apple version

3.1.1

### rules_swift version

I do not how to tell this version.

**Comment by brentleyjones** [comment]
The WORKSPACE snippet includes the information needed to resolve this.

**Comment by brentleyjones** [comment]
If that doesn't work for you, please provide a reproduction that we can run to see the same issue.
