### ISSUE TITLE
Bug: Local breakpoints aren't persisted between project generations

### ISSUE THREAD

**Issue by marcelofabri** [MobileNativeFoundation/rules_xcodeproj#2697]
I've noticed that any breakpoints defined in `SomeProject.xcodeproj/xcuserdata/SomeUser.xcuserdatad/xcdebugger` are deleted after a project is re-regenerated.

We'll probably fix this in our wrapper script, but decided to open this issue as it'd be cool for the default generator to keep any `xcdebugger` files between runs.

**Comment by adincebic** [comment]
This should work as expected with new incremental generators. @brentleyjones perhaps can provide more details.

**Comment by brentleyjones** [comment]
I would say this is a bug. I can fix it Monday.

**Comment by brentleyjones** [comment]
(I will say I personally haven't seen this, but I'll be sure to dig into it regardless.)
