### ISSUE TITLE
Bug: error when using '--linkopt="-fuse-ld=lld"'

### ISSUE THREAD

**Issue by Augustyniak** [MobileNativeFoundation/rules_xcodeproj#2719]
### Description

in my `.rc` file I have

```
build:rules_xcodeproj --linkopt="-fuse-ld=lld"
```

After generating an Xcode project and attempting to compile it from within Xcode I get the following error:

```
/var/tmp/_bazel_rafal/41728fd1c90dcca3847c5c93f7368518/rules_xcodeproj.noindex/build_output_base/execroot/__main__/clang:1:1 invalid linker name in argument '-fuse-ld=lld'
```

I use `bazel` `build_mode` and have `llvm` as part of my `PATH`.

### Reproduction steps

1. add the following statement to your `.rc` file:

```
build:rules_xcodeproj --linkopt="-fuse-ld=lld"
```

2. Generate Xcode project
3. Compile project

### Expected behavior

Build completes with a success.

### rules_xcodeproj version

1.12.1

### Xcode version

15.0

### Bazel version

7.0.0-pre.20230917.3

**Comment by brentleyjones** [comment]
What is your `ios` config set to?

Also, adjusting the `examples/integration` project, or creating a full repro, with steps to reproduce (in the case of the llvm stuff if needed) would help here.

**Comment by brentleyjones** [comment]
> have llvm as part of my `PATH`

I think you'll need to adjust [`xcodeproj.bazel_env`](https://github.com/MobileNativeFoundation/rules_xcodeproj/blob/main/docs/bazel.md#xcodeproj-bazel_env) to include the same adjustment. The default is a limited `PATH`.

**Comment by brentleyjones** [comment]
@Augustyniak did my suggestion work for you?
