### ISSUE TITLE
Bug: xcode-installer.sh: line 171: USER: unbound variable

### ISSUE THREAD

**Issue by erikkerber** [MobileNativeFoundation/rules_xcodeproj#2730]
### Description

```
INFO: Streaming build results to: https://app.buildbuddy.io/invocation/ae1b2350-c832-4c6f-9682-bc6d2c0ff814
/private/var/tmp/_bazel_ekerber/5640f185ae43872669b5907956acd71d/rules_xcodeproj.noindex/build_output_base/execroot/_main/bazel-out/darwin_arm64-dbg/bin/external/rules_xcodeproj~override~internal~rules_xcodeproj_generated/generator/App/xcode/xcode-installer.sh: line 171: USER: unbound variable
```

### Reproduction steps

1. Don't pass `$USER` in `tools/bazel`
2. Run under incremental generation mode

### Expected behavior

Generates

### rules_xcodeproj version

integrity = "ssha256-oCXa63u6OSobUh3n2TDSS2Iq3ySPhyTcLwJPb76/f8c="

### Xcode version

15.0.0

### Bazel version

7.0.0rc4

### Additional information

Nov 16 archive

integrity = "ssha256-oCXa63u6OSobUh3n2TDSS2Iq3ySPhyTcLwJPb76/f8c="

**Comment by brentleyjones** [comment]
Hmm. We need to know `$USER` in order to correctly create the `xcschememanagement.plist` file. We technically could not create that file, but then schemes won't be sorted correctly. So maybe I'll just put an annoying warning saying that `$USER` should be set and explain what the installer can't do.

**Comment by brentleyjones** [comment]
I can use `/usr/bin/id -un` instead.

**Comment by brentleyjones** [comment]
Should be fixed in the latest preview.
