### ISSUE TITLE
Bug: Migrating from Tulsi to rules_xcodeproj

### ISSUE THREAD

**Issue by ymh514** [MobileNativeFoundation/rules_xcodeproj#2731]
### Description

Hello rules_xcodeproj Community,

I am navigating the process of migrating a project from Tulsi to rules_xcodeproj and have encountered several issues. I am reaching out for assistance and would also like to share feedback about this migration process.

### 1. Original Tulsi Configuration:
* Project Name: TargetSDK
* Build Targets: //project/objc/demo:AppTarget
* Bazel Build Options:
* Debug: `--copt -DSTREAMER_FROM_SOURCE_CODE --//project/graphs/demo:extra_assets=full`
* Release: `--copt -DSTREAMER_FROM_SOURCE_CODE`
* .tulsigen like:
```
{
  "buildTargets" : [
    "//project/objc/demo:AppTarget"
  ],
  "optionSet" : {
    "BazelBuildOptionsDebug" : {
      "p" : "$(inherited)",
      "t" : {
        "//project/objc/demo:AppTarget" : "--copt -DBUILD_FROM_SOURCE_CODE --//project/graphs/demo:extra_assets=full"
      }
    },
    "BazelBuildOptionsRelease" : {
      "p" : "$(inherited)",
      "t" : {
        "//project/objc/demo:AppTarget" : "--copt -DBUILD_FROM_SOURCE_CODE"
      }
    },
    ...
  },
  "projectName" : "TargetSDK",
  "sourceFilters" : [
    ...
  ]
}
```

### 2. Attempted rules_xcodeproj Configuration
```
xcodeproj(
    name = "AppTarget_xcodeproj",
    build_mode = "bazel",
    project_name = "AppTarget",
    top_level_targets = [
        top_level_target("//project/objc/demo:AppTarget", target_environments = ["device"]),
    ],
    xcode_configurations = {
        "Debug": {
            "//command_line_option:compilation_mode": "dbg",
            "//project/graphs/demo:extra_assets": "full",
        },
        "Release": {
            "//command_line_option:compilation_mode": "opt",
            "//project/graphs/demo:extra_assets": "none",
        },
    },
    scheme_autogeneration_mode = "auto",
    tags = ["manual"],
    visibility = ["//visibility:public"],
)
```

### 3. config_settings for assets:
```
config_setting(
    name = "full",
    flag_values = {
        ":extra_assets": "full",
    }
)

filegroup(
    name = "bundle_assets",
    srcs = [...],
) + select({
    ":full": [
        "//project/models:model1",
        "//project/models:model2",
        // ... additional models and resources
    ],
    "//conditions:default": [],
})
```

### 1. run command in terminal:
```
bazel run //project/objc/demo:AppTarget_xcodeproj --@rules_xcodeproj//xcodeproj:extra_common_flags="--copt -DBUILD_FROM_SOURCE_CODE --//project/graphs/demo:extra_assets=full"
```

### Expected behavior

The key expectation from the above reproduction steps centered around the handling of extra_assets in the debug scheme:

1. Packing extra_assets in Debug Scheme:
    * My expectation was that in the debug scheme,` extra_assets` as specified in the `rules_xcodeproj` configuration would be correctly packed into the app, replicating the behavior observed in the Tulsi setup. This entails the inclusion and bundling of all designated assets during the build process in debug mode.

2. Consistency with Tulsi Configuration:
    * The `rules_xcodeproj` behavior was anticipated to closely mirror the Tulsi setup's success in asset packing. I expected a seamless process with no errors or discrepancies in the assets included in the debug build of the app, ensuring a smooth and consistent migration experience.

The primary objective of this migration was to maintain the functionality and reliability of the Tulsi configuration, especially regarding the inclusion of `extra_assets` in the debug version of the application.

### rules_xcodeproj version

1.13.0

### Xcode version

14.2

### Bazel version

6.0.0

### rules_apple version

2.5.0

### rules_swift version

1.2.0

**Comment by luispadron** [comment]
Hi!

Is `bundle_assets` used by your `AppTarget` at all? Dont see the BUILD file for it. You could double check the build logs in Xcode to see if the flags are sent correctly when you switch settings as well. That would be helpful to debug further.

**Comment by ymh514** [comment]
> Hi!
> 
> Is `bundle_assets` used by your `AppTarget` at all? Dont see the BUILD file for it. You could double check the build logs in Xcode to see if the flags are sent correctly when you switch settings as well. That would be helpful to debug further.

Hi,

Thank you for your quick response!

Yes, bundle_assets is indeed utilized in AppTarget. Here is the relevant portion from the BUILD file to illustrate its use:

```starlark
ios_application(
    name = "AppTarget",
    visibility = ["//visibility:public"],
    ...
    deps = [
        ":AppTargetLibrary",
        ...
    ],
)

objc_library(
    name = "AppTargetLibrary",
    ...
    data = [
        "//project/models:bundle_assets"
    ],
    ...
)
```
Regarding the build logs in Xcode, I have not yet checked them. I will take a look at the logs to see if the flags are correctly applied when switching settings. This could provide further insights into the issue.

Thanks again for your help!

**Comment by ymh514** [comment]
Hi @luispadron,

In my previous setup with Tulsi, I was able to see the exact Bazel command used when running a target in Xcode. This visibility helped in understanding and debugging the build process. 
```txt
/opt/homebrew/Cellar/bazelisk/1.17.0/bin/bazelisk build --verbose_failures --bes_outerr_buffer_size=0 --copt -DBUILD_FROM_SOURCE_CODE --//project/graphs/demo:extra_assets=full --apple_platform_type=ios --cpu=ios_arm64 --watchos_cpus=armv7k,arm64_32 --announce_rc '--override_repository=tulsi=/Users/jesse/Library/Application Support/Tulsi/0.20220209.88/Bazel' --compilation_mode=dbg --define=apple.add_debugger_entitlement=1 --define=apple.propagate_embedded_extra_outputs=1 --define=apple.experimental.tree_artifact_outputs=1 --features=debug_prefix_map_pwd_is_dot --tool_tag=tulsi:bazel_build --build_event_json_file=/Users/jesse/iosProjects/Tulsi/AppTarget.xcodeproj/.tulsi/40100_build_events.json --noexperimental_build_event_json_file_path_conversion --aspects @tulsi//:tulsi/tulsi_aspects.bzl%tulsi_outputs_aspect --output_groups=+tulsi_outputs //project/objc/demo:AppTarget
```

However, in the rules_xcodeproj environment, I haven't been able to find where the Bazel command is specified or logged when building and running a target.

Could you please guide me on where to find the Bazel command in rules_xcodeproj? Knowing this would greatly assist in comparing the build processes and debugging the current issue.

Thank you for your assistance.

**Comment by ymh514** [comment]
Hi 
I found that running 
```
bazel run //project/objc/demo:AppTarget_xcodeproj --@rules_xcodeproj//xcodeproj:extra_common_flags="--//project/graphs/demo:extra_assets=full --copt -DBUILD_FROM_SOURCE_CODE"
```
resolves the issue I was facing. It turns out my resources were not configured correctly.
Thank you for your assistance!
