### ISSUE TITLE
Bug: no such package '@rules_xcodeproj~1.13.0~internal~rules_xcodeproj_generated//generator/Sources/xcodeproj'

### ISSUE THREAD

**Issue by DanielLiuCD** [MobileNativeFoundation/rules_xcodeproj#2741]
### Description

I used bazel for the first time and created the following bazel project. The test build can pass, but the xcode project cannot be created.

Report the following error：

```
Generating "Sources/RemoteResource.xcodeproj"
ERROR: Skipping '@@rules_xcodeproj~1.13.0~internal~rules_xcodeproj_generated//generator/Sources/xcodeproj': no such package '@rules_xcodeproj~1.13.0~internal~rules_xcodeproj_generated//generator/Sources/xcodeproj': The repository '@rules_xcodeproj~1.13.0~internal~rules_xcodeproj_generated' could not be resolved: Repository '@rules_xcodeproj~1.13.0~internal~rules_xcodeproj_generated' is not defined
WARNING: Target pattern parsing failed.
ERROR: no such package '@rules_xcodeproj~1.13.0~internal~rules_xcodeproj_generated//generator/Sources/xcodeproj': The repository '@rules_xcodeproj~1.13.0~internal~rules_xcodeproj_generated' could not be resolved: Repository '@rules_xcodeproj~1.13.0~internal~rules_xcodeproj_generated' is not defined
```

### Reproduction steps

load("@build_bazel_rules_apple//apple:ios.bzl", "ios_application")
load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")
load("@rules_xcodeproj//xcodeproj:defs.bzl", "top_level_target", "xcodeproj")

swift_library(
    name = "lib",
    srcs = glob(["src/*.swift"]),
)

ios_application(
    name = "iOSApp",
    bundle_id = "bazel.daniel.remoteresource",
    families = [
        "iphone",
        "ipad",
    ],
    infoplists = ["Resources/Info.plist"],
    minimum_os_version = "17.0",
    visibility = ["//visibility:public"],
    deps = [":lib"],
)

xcodeproj(
    name = "xcodeproj",
    build_mode = "bazel",
    project_name = "RemoteResource",
    tags = ["manual"],
    top_level_targets = [
        ":iOSApp",
    ],
)

### Expected behavior

Able to create xcode projects

### rules_xcodeproj version

1.13.0

### Xcode version

15.0.1

### Bazel version

6.4.0

### Additional information

[RemoteResource.zip](https://github.com/MobileNativeFoundation/rules_xcodeproj/files/13495724/RemoteResource.zip)
This is my demo project

**Comment by mattrobmattrob** [comment]
[RemoteResource.zip](https://github.com/MobileNativeFoundation/rules_xcodeproj/files/13495724/RemoteResource.zip)  with these files added:
```diff
diff --git a/.bazelrc b/.bazelrc
new file mode 100644
index 0000000..3ce91d2
--- /dev/null
+++ b/.bazelrc
@@ -0,0 +1 @@
+common --enable_bzlmod
diff --git a/.bazelversion b/.bazelversion
new file mode 100644
index 0000000..19b860c
--- /dev/null
+++ b/.bazelversion
@@ -0,0 +1 @@
+6.4.0
```
The follow command works to generate the project:
```
$ bazel run //Sources:xcodeproj
INFO: Analyzed target //Sources:xcodeproj (8 packages loaded, 18 targets configured).
INFO: Found 1 target...
Target //Sources:xcodeproj up-to-date:
  bazel-bin/Sources/xcodeproj-runner.sh
INFO: Elapsed time: 16.849s, Critical Path: 0.07s
INFO: 11 processes: 10 internal, 1 local.
INFO: Build completed successfully, 11 total actions
INFO: Running command line: bazel-bin/Sources/xcodeproj-runner.sh

Generating "Sources/RemoteResource.xcodeproj"
Starting local Bazel server and connecting to it...
INFO: Analyzed target @rules_xcodeproj~1.13.0~internal~rules_xcodeproj_generated//generator/Sources/xcodeproj:xcodeproj (105 packages loaded, 1403 targets configured).
INFO: Found 1 target...
INFO: Elapsed time: 9.909s, Critical Path: 0.71s
INFO: 42 processes: 34 internal, 8 local.
INFO: Build completed successfully, 42 total actions
INFO: Running command line: /private/var/tmp/_bazel_mattrobinson/345336f63bc90e260213cf73a31a736b/rules_xcodeproj.noindex/build_output_base/execroot/_main/bazel-out/darwin_arm64-dbg/bin/external/rules_xcodeproj~1.13.0~internal~rules_xcodeproj_generated/generator/Sources/xcodeproj/xcodeproj-installer.sh --xcodeproj_bazelrc /private/var/tmp/_bazel_mattrobinson/345336f63bc90e260213cf73a31a736b/execroot/_main/bazel-out/darwin_arm64-fastbuild/bin/Sources/xcodeproj-runner.sh.runfiles/_main/Sources/xcodeproj.bazelrc --extra_flags_bazelrc /private/var/tmp/_bazel_mattrobinson/345336f63bc90e260213cf73a31a736b/execroot/_main/bazel-out/darwin_arm64-fastbuild/bin/Sources/xcodeproj-runner.sh.runfiles/_main/Sources/xcodeproj-extra-flags.bazelrc --bazel_path /Users/mattrobinson/Library/Caches/bazelisk/downloads/bazelbuild/bazel-6.4.0-darwin-arm64/bin/bazel --execution_root /private/var/tmp/_bazel_mattrobinson/345336f63bc90e260213cf73a31a736b/execroot/_main
Updated project at "Sources/RemoteResource.xcodeproj"
```

Does that solve it for you in your setup? Can you improve the repro to match the error in your project if it doesn't?

**Comment by mattrobmattrob** [comment]
I'm going to close this for now since I've solved the issue in the repro project. Please re-open if you need more assistance/provide an example of what doesn't work in the repro project. 🙏

**Comment by DanielLiuCD** [comment]
> I'm going to close this for now since I've solved the issue in the repro project. Please re-open if you need more assistance/provide an example of what doesn't work in the repro project. 🙏

Thank you very much for your help. I noticed that I can't succeed using the command "bazelisk run --enable_bzlmod //Sources:xcodeproj". I can succeed using bazelrc. Is there any documentation that can explain why this is? I looked for the bazel documentation and there is nothing Find any relevant instructions

**Comment by brentleyjones** [comment]
Flags applied at the command-line don't get applied to parts of rules_xcodeproj because of its nested bazel invocations architecture.

While we don't explicitly spell that out anywhere (and we should...), more details can be found here: https://github.com/MobileNativeFoundation/rules_xcodeproj/blob/main/docs/usage.md
