### ISSUE TITLE
Feature Request: Allow setting additional environment variables in `Test` action

### ISSUE THREAD

**Issue by thii** [MobileNativeFoundation/rules_xcodeproj#2742]
Currently the environment variables in the scheme's `Test` action are already inherited from the `_test` target's `env` attribute. But there are use cases where environment variables don't have fixed values, so it's not possible to define them in the target definition. This would be possible if we can define additional Xcode build settings in the generated Xcode project, then expand them in the target:

```
ios_ui_test(
    ...
    env = {"MY_VAR": "$(MY_VAR)"},
    ...
)
```

**Comment by brentleyjones** [comment]
The test you have defined there, wouldn't be runnable outside of Xcode then, right? I'm hesitant to add capabilities that make it possible to have a target only work in Xcode, but not with `bazel test`. How would you do this outside of Xcode?

**Comment by thii** [comment]
The variable is optional, so it can run outside of Xcode, but we always run this with Xcode or `xcodebuild`.

**Comment by thii** [comment]
That would work. But I don't really like to manage yet another git-ignored file. Is there a way take certain environment variables and make them available in test? I thought this worked in Bazel but when I tried, it didn't:

```
$ export MY_VAR=value
```

```
# .bazelrc
test --test_env=MY_VAR
```

**Comment by brentleyjones** [comment]
That should work, but you'll need to adjust `xcodeproj.bazel_env` to include `MY_VAR`.

**Comment by thii** [comment]
I'll need to look a bit more but this was the only way that I saw it generated correctly in the Xcode project.

```
# .bazelrc
build --test_env=MY_VAR=value
```

**Comment by brentleyjones** [comment]
Seems like the desire for this went away? Ping if that's not the case.
