### ISSUE TITLE
[Incremental] Bug: `library_targets` required for `top_level_anchor_target`, docs show `None` as an option

### ISSUE THREAD

**Issue by erikkerber** [MobileNativeFoundation/rules_xcodeproj#2827]
### Description

Defining a `top_level_anchor_target` without `library_targets` results in:

> `library_targets` must be non-empty for `xcscheme.top_level_anchor_target

Docs show it is not a required field

### Reproduction steps

(Description)

### Expected behavior

Either `library_targets` is optional, or docs reflect that it is not.

### rules_xcodeproj version

1.14.0

### Xcode version

15.1

### Bazel version

7

**Comment by brentleyjones** [comment]
It is required. It's the point of that version versus the non-anchor one.

None isn't an option, it's just the default.

**Comment by brentleyjones** [comment]
I don't think there is an actual issue here. Please let me know if I am misunderstanding though.
