### ISSUE TITLE
Bug: The generated Xcode project does not include the source files from cmake

### ISSUE THREAD

**Issue by yyl1989726** [MobileNativeFoundation/rules_xcodeproj#2831]
### Description

I want to compile a cmake project using Bazel and manage its source code dependencies. However, I've noticed that while the generated project runs correctly, it does not include the source files contained in cmake, preventing me from setting breakpoints.

### Reproduction steps

The file directory is as follows:
![image](https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/8705722/5b629670-fc13-461f-baaf-7838f85a09be)

The BUILD file under 'vendor' contains the following code, 
![image](https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/8705722/cee5249a-e59f-48ba-bd80-c226e0a18ab7)

The BUILD file in the outer layer contains the following 
![image](https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/8705722/da99e65b-3ea9-43d8-b38f-9e55d2c07e48)

The generated Xcode project, as  following, can run normally. However, the project does not display the files 'hello.c' and 'hello.h'. This prevents setting breakpoints.
![image](https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/8705722/b813f20d-6cc2-4745-a5f5-7e7b9a5a3be8)

### Expected behavior

The generated project includes the relevant source code from CMake, that is, it contains the files 'hello.c' and 'hello.h’

### rules_xcodeproj version

f5c1f4bea9f00732ef9d54d333d9819d574de7020dbd9d081074232b93c10b2c

### Xcode version

Version 15.0 (15A240d)

### Bazel version

bazel 6.4.0-homebrew

**Comment by brentleyjones** [comment]
Can you attach a self-contained repro that we can debug?

**Comment by yyl1989726** [comment]
https://github.com/yyl1989726/bazel_cmake_xcodeproj_demo/tree/main

**Comment by brentleyjones** [comment]
I can't generate the project, I get this error:
```
Download from https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz failed: class java.net.ConnectException Connection refused
```

**Comment by brentleyjones** [comment]
I assume it's my network for some reason. I'll try again later.

**Comment by f0rmiga** [comment]
@brentleyjones freedesktop.org has been down for the best part of the day. It's not you.

**Comment by f0rmiga** [comment]
You can use temporarily:
```rules_foreign_cc_dependencies(register_built_pkgconfig_toolchain = False)```

**Comment by brentleyjones** [comment]
#2847 fixes this:
![CleanShot 2024-01-04 at 10 17 49@2x](https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/158658/1b2221b2-c789-46a8-90d9-956e07abcc2d)
