### ISSUE TITLE
[Incremental] Bug: generated xcodeproj diffs from incremental mode and legacy mode when given same focused targets

### ISSUE THREAD

**Issue by LLlkaiwen** [MobileNativeFoundation/rules_xcodeproj#2834]
### Description

xcodeproj generated in incremental mode:
<img width="1092" alt="image" src="https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/35733740/3d59c12b-ddd3-4030-b46a-8c07454edfce">
xcodeproj generated in legacy mode:
<img width="1348" alt="image" src="https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/35733740/97f55bea-f5e0-43b5-b2e5-2f96e14e71a4">

### Reproduction steps

1. Add focused_targets 
<img width="837" alt="image" src="https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/35733740/0a8c4bd5-1d61-462d-8053-d607d494899e">
2. remove unneeded xcschemes
3. run `bazel run //tools:xcodeproj`

### Expected behavior

Should the target 'swift_debug_settings (Library)' be added ?

### rules_xcodeproj version

1.14.2

### Xcode version

15.0

### Bazel version

7.0.0

**Comment by brentleyjones** [comment]
This isn't a bug, just a change in how `focused_targets` works in incremental generation mode. It's now taken literally, so if you want the files from the library target, it needs to be focused as well. 

This change in behavior is needed to support some of the performance wins that incremental generation achieves. It's also less confusing (in the long run).

**Comment by brentleyjones** [comment]
Though, when you do add that library target the incremental generation will have an improved result over legacy: the target will be able to be merged with both the test and the tool. So it won't show in the target list like it does for legacy mode.
