### ISSUE TITLE
[Incremental] Bug: Not support in Bazel 5

### ISSUE THREAD

**Issue by LLlkaiwen** [MobileNativeFoundation/rules_xcodeproj#2843]
### Description

![image](https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/35733740/e78f97f1-e66f-4aeb-811f-65f9b7d54fbb)
As shown in README, it is compatible with Bazel 5.3 - 6.x. 
But function 'native.package_relative_label' which added in Bazel 6.1.0 is used in incremental generation mode. 
<img width="1085" alt="image" src="https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/35733740/a7302021-0288-40ad-b51b-e14e3ee2d280">

### Reproduction steps

No steps

### Expected behavior

The new incremental generation mode can be used in Bazel 5.4

### rules_xcodeproj version

1.14.2

### Xcode version

15.1

### Bazel version

5.4

**Comment by brentleyjones** [comment]
I'll see if we can continue to support Bazel 5 with incremental generation mode.

**Comment by brentleyjones** [comment]
There are other Bazel 6 changes that we depend on, so we won't be able to support Bazel 5 with incremental generation mode. I'll update the README to reflect this.
