### ISSUE TITLE
Feature Request: Support building for arm64 iOS

### ISSUE THREAD

**Issue by jpsim** [MobileNativeFoundation/rules_xcodeproj#285]
First of all, thanks for creating and sharing this project. I'm looking forward to trying this to integrate with [Envoy Mobile](https://github.com/envoyproxy/envoy-mobile).

One of our main use cases for Xcode integration is to run [our iOS example apps](https://github.com/envoyproxy/envoy-mobile/tree/main/examples/swift) on physical iOS devices.

I'm not sure if this is something that rules_xcodeproj is intended to currently support and I'm using it wrong, or if this is a feature that hasn't been built yet, so I've labeled this as a feature request more than a bug.

Currently, if I run `bazel run //:xcodeproj` from `examples/ios_app` in this repo, open the project in Xcode, update the code signing section for the "Example" iOS app target to the following:

<img width="626" alt="image" src="https://user-images.githubusercontent.com/474794/163023103-837e3d77-b40f-4dfc-8e51-6fd0a677313d.png">

and attempt to build for a device (or build and run) I see the following error message in the Xcode build logs:

> rules_xcodeproj/examples/ios_app/Example/ContentView.swift:2:8: Module 'ExternalFramework' was created for incompatible target arm64-apple-ios12.0-simulator: /var/tmp/_bazel_jsimard/e1a0d3a6038bce3f1a38641ac8938150/external/examples_ios_app_external/ExternalFramework.framework/Modules/ExternalFramework.swiftmodule/arm64.swiftmodule

Possibly because I've already built and run for a local simulator. I tried running `bazel clean --expunge` and cmd-shift-k in Xcode and the error persists.

If this is a bug and iOS device support is intended to work, I'd appreciate if you could share a workaround for the issue (am I cleaning the wrong thing?).

If building for iOS devices isn't currently supported then please consider this to be a feature request for that functionality 😄.

I imagine the fact that I'm on an M1 Mac may be a contributor to this issue, since I've already built the example app for an arm64 simulator and Xcode/bazel/rules_xcodeproj is getting confused between arm64 iOS simulator and arm64 iOS device.

**Comment by brentleyjones** [comment]
Running on device currently isn't supported. Thank you for detailed the feature request though. I'll see if there is a quick work around for the time being (or if I can just unblock it all-together).

**Comment by jpsim** [comment]
With `build_mode = "bazel"`, and adding `provisioning_profile = "...",` to the `ios_application` definition, and adding `build --ios_multi_cpus=arm64` to the `.bazelrc`, building and running on a physical device in Xcode works for my project!

I do need to clean in Xcode (cmd-shift-k) between runs though.

**Comment by brentleyjones** [comment]
>I do need to clean in Xcode (cmd-shift-k) between runs though.

Between each run, even if you don't change anything? Can you share the errors you are getting?

**Comment by jpsim** [comment]
First I get an `Unable to install "app"` error modal:

<img width="263" alt="image" src="https://user-images.githubusercontent.com/474794/167486941-6ff44089-74ff-43f9-b86a-fc77b246f39c.png">

Then clicking "Details" shows `An unknown error has occurred.`

<details>
<summary>Details</summary>

```
Details

Unable to install "app"
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620415
User Info: {
    DVTErrorCreationDateKey = "2022-05-09 19:52:34 +0000";
    IDERunOperationFailingWorker = IDEInstalliPhoneLauncher;
}
--
An unknown error has occurred.
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620415
User Info: {
    DVTRadarComponentKey = 280331;
    MobileDeviceErrorCode = "(0xE8008001)";
    "com.apple.dtdevicekit.stacktrace" = (
	0   DTDeviceKitBase                     0x00000001293debec DTDKCreateNSErrorFromAMDErrorCode + 272
	1   DTDeviceKitBase                     0x000000012941a3f4 __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 160
	2   DVTFoundation                       0x000000010441b94c DVTInvokeWithStrongOwnership + 76
	3   DTDeviceKitBase                     0x000000012941a144 -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1312
	4   IDEiOSSupportCore                   0x00000001292e3a60 __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.292 + 2908
	5   DVTFoundation                       0x000000010454666c __DVT_CALLING_CLIENT_BLOCK__ + 16
	6   DVTFoundation                       0x0000000104547c58 __DVTDispatchAsync_block_invoke + 564
	7   libdispatch.dylib                   0x0000000185ba4604 _dispatch_call_block_and_release + 32
	8   libdispatch.dylib                   0x0000000185ba61c8 _dispatch_client_callout + 20
	9   libdispatch.dylib                   0x0000000185bad8a8 _dispatch_lane_serial_drain + 668
	10  libdispatch.dylib                   0x0000000185bae404 _dispatch_lane_invoke + 392
	11  libdispatch.dylib                   0x0000000185bb8c98 _dispatch_workloop_worker_thread + 648
	12  libsystem_pthread.dylib             0x0000000185d66360 _pthread_wqthread + 288
	13  libsystem_pthread.dylib             0x0000000185d65080 start_wqthread + 8
);
}
--

Analytics Event: com.apple.dt.IDERunOperationWorkerFinished : {
    "device_model" = "iPhone14,2";
    "device_osBuild" = "15.5 (19F5062g)";
    "device_platform" = "com.apple.platform.iphoneos";
    "launchSession_schemeCommand" = Run;
    "launchSession_state" = 1;
    "launchSession_targetArch" = arm64;
    "operation_duration_ms" = 780;
    "operation_errorCode" = "-402620415";
    "operation_errorDomain" = "com.apple.dt.MobileDeviceErrorDomain";
    "operation_errorWorker" = IDEInstalliPhoneLauncher;
    "operation_name" = IDEiPhoneRunOperationWorkerGroup;
    "param_consoleMode" = 0;
    "param_debugger_attachToExtensions" = 0;
    "param_debugger_attachToXPC" = 1;
    "param_debugger_type" = 5;
    "param_destination_isProxy" = 0;
    "param_destination_platform" = "com.apple.platform.iphoneos";
    "param_diag_MainThreadChecker_stopOnIssue" = 0;
    "param_diag_MallocStackLogging_enableDuringAttach" = 0;
    "param_diag_MallocStackLogging_enableForXPC" = 1;
    "param_diag_allowLocationSimulation" = 1;
    "param_diag_gpu_frameCapture_enable" = 0;
    "param_diag_gpu_shaderValidation_enable" = 0;
    "param_diag_gpu_validation_enable" = 0;
    "param_diag_memoryGraphOnResourceException" = 0;
    "param_diag_queueDebugging_enable" = 1;
    "param_diag_runtimeProfile_generate" = 0;
    "param_diag_sanitizer_asan_enable" = 0;
    "param_diag_sanitizer_tsan_enable" = 0;
    "param_diag_sanitizer_tsan_stopOnIssue" = 0;
    "param_diag_sanitizer_ubsan_stopOnIssue" = 0;
    "param_diag_showNonLocalizedStrings" = 0;
    "param_diag_viewDebugging_enabled" = 1;
    "param_diag_viewDebugging_insertDylibOnLaunch" = 1;
    "param_install_style" = 0;
    "param_launcher_UID" = 2;
    "param_launcher_allowDeviceSensorReplayData" = 0;
    "param_launcher_kind" = 0;
    "param_launcher_style" = 0;
    "param_launcher_substyle" = 0;
    "param_runnable_appExtensionHostRunMode" = 0;
    "param_runnable_productType" = "com.apple.product-type.application";
    "param_runnable_swiftVersion" = "5.5.2";
    "param_runnable_type" = 2;
    "param_testing_launchedForTesting" = 0;
    "param_testing_suppressSimulatorApp" = 0;
    "param_testing_usingCLI" = 0;
    "sdk_canonicalName" = "iphoneos15.2";
    "sdk_osVersion" = "15.2";
    "sdk_variant" = iphoneos;
}
--


System Information

macOS Version 12.3.1 (Build 21E258)
Xcode 13.2.1 (19586) (Build 13C100)
Timestamp: 2022-05-09T15:52:34-04:00
```

</details>
