### ISSUE TITLE
[Incremental] Bug: Index failed: 'fatal error: virtual filesystem overlay file not found'

### ISSUE THREAD

**Issue by LLlkaiwen** [MobileNativeFoundation/rules_xcodeproj#2852]
### Description

Index failed when run examples/rules_ios in `incremental mode`. Howerver it works in `legacy mode`.
Detail error shown as below:
`fatal error: virtual filesystem overlay file '/*/rules_xcodeproj/examples/rules_ios/bazel-output-base/rules_xcodeproj.noindex/indexbuild_output_base/execroot/_main/bazel-out/ios-sim_arm64-min15.0-applebin_ios-ios_sim_arm64-dbg-ST-a4a9813474a3/bin/iOSApp/Test/MixedUnitTests/iOSAppMixedUnitTests_vfs.yaml' not found`

### Reproduction steps

1. checkout to main branch (currently at commit 46f7a1f47c02e8bec3398913c5d018dd3cc71da5) of 'rules_xcodeproj'
2. cd examples/rules_ios
3. run `bazel run //:xcodeproj-incremental`
4. open rules_ios.xcodeproj
5. wait for Index

### Expected behavior

Index works in incremental mode.

### rules_xcodeproj version

46f7a1f47c02e8bec3398913c5d018dd3cc71da5

### Xcode version

15.1

### Bazel version

7.0.0

**Comment by LLlkaiwen** [comment]
That vfsoverlay file is produced by Bazel target defined by rule [framework_vfs_overlay](https://github.com/bazel-ios/rules_ios/blob/8c7513d1cb62cfc86bd2f87f01871c1abc3f00e9/rules/framework/vfs_overlay.bzl#L425), which is considered as unsupported target in both `incremental mode` and `legacy mode`.

**Comment by brentleyjones** [comment]
Thanks for the detailed report. I'm looking into it.

**Comment by brentleyjones** [comment]
Which file failed to index? do you have a fuller error? I'm not able to reproduce this. I _do_ get this error:

```
/<unknown>: error: cannot open file '/*/rules_xcodeproj/examples/rules_ios/bazel-output-base/rules_xcodeproj.noindex/indexbuild_output_base/execroot/_main/bazel-out/ios-sim_arm64-min15.0-applebin_ios-ios_sim_arm64-dbg-ST-a4a9813474a3/bin/iOSApp/Test/MixedUnitTests/iOSAppMixedUnitTests_swift_vfs.yaml' (No such file or directory)
```

But it goes away once the correct `Index Build` that generates that file finishes.

**Comment by LLlkaiwen** [comment]
<img width="1436" alt="image" src="https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/35733740/5f63288e-acd9-45a1-acc0-bb5a3b4b673f">
It's file `rules_xcodeproj/examples/rules_ios/iOSApp/Test/MixedUnitTests/ObjCUnitTests.m`. And as shown in the above picture, there are also some other files  failed due to `virtual filesystem overlay file not found`

**Comment by LLlkaiwen** [comment]
The errors occur in process of `Indexing`, at which time the `Index Build` has already finished.

**Comment by brentleyjones** [comment]
Thanks! #2859 fixed that in my testing.
