### ISSUE TITLE
1.15 Release URL points to 1.14 archive

### ISSUE THREAD

**Issue by Jon-Schneider** [MobileNativeFoundation/rules_xcodeproj#2867]
### Description

In [the 1.15 release snippet](https://github.com/MobileNativeFoundation/rules_xcodeproj/releases/tag/1.15.0), the download URL points to 1.14.0 instead of 1.15.0.

```
http_archive(
    name = "rules_xcodeproj",
    sha256 = "7775beba1f9ddb3cbce209ca1ed0d117ffe28b92d85bfa8e659fb3c176ada565",
    url = "https://github.com/MobileNativeFoundation/rules_xcodeproj/releases/download/1.14.0/release.tar.gz",
)
```

### Reproduction steps

Using this http_archive snippet as-is will fail because the download doesn't match the hash.

### Expected behavior

Using this http_archive snippet should point to the 1.15.0 download URL.

### rules_xcodeproj version

1.15.0

### Xcode version

All

### Bazel version

All

**Comment by brentleyjones** [comment]
Thanks for the report! I’ve edited the release notes.
