### ISSUE TITLE
Bug: XCBuildData/PIFCache) doesn't exist

### ISSUE THREAD

**Issue by 315567599** [MobileNativeFoundation/rules_xcodeproj#2942]
### Description

xcode archive error:

PIFCache (/Users/jiangchao/Library/Developer/Xcode/DerivedData/xx-einijeybeftdgffqsashuprvowio/Build/Intermediates.noindex/ArchiveIntermediates/xx/IntermediateBuildFilesPath/XCBuildData/PIFCache) doesn't exist. If you manually cleared Derived Data, you need to close and re-open the project for the PIFCache to be created again. Using the "Clean Build Folder" command instead (⇧ ⌘ K) won't trigger this error. If this error still happens after re-opening the project, please file a bug report here: https://github.com/MobileNativeFoundation/rules_xcodeproj/issues/new?template=bug.md

### Reproduction steps

bt

### Expected behavior

work

### rules_xcodeproj version

1.16

### Xcode version

15.2

### Bazel version

6.1.1

### rules_apple version

3.3.0

### rules_swift version

1.16.0

**Comment by brentleyjones** [comment]
The archive action isn't supported: https://github.com/MobileNativeFoundation/rules_xcodeproj/blob/main/docs/faq.md#does-the-archive-action-work
