### ISSUE TITLE
Bug: Xcode Previews failing in extensions

### ISSUE THREAD

**Issue by andre-alves** [MobileNativeFoundation/rules_xcodeproj#2997]
### Description

I'm not sure if it's a recent regression or not, but Xcode Previews is not working with extensions:

```
The app extension ”WidgetExtension.appex” needs to be embedded in an app in order to use previews
```

<img width="2260" alt="image" src="https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/7773955/423aca8d-d525-451e-84a7-124cfe910777">

### Reproduction steps

It's possible to reproduce using the integration example without any changes:

- `cd examples/integration`
- `bazel run //:xcodeproj-incremental-bazel-sim_arm64`
- `open Integration.xcodeproj`
- Select  scheme`iOSApp` or `WidgetExtension in iOSApp` 
- Open `WidgetExtension.swift` and check previews

### Expected behavior

Xcode Previews to display.

### rules_xcodeproj version

main (de3089fd2612fc97299e87955975e1dc34049b67)

### Xcode version

15.2

### Bazel version

7.1.0

### rules_apple version

3.5.0

### rules_swift version

1.18.0

**Comment by andre-alves** [comment]
Got it! Xcode Previews just need explicit dependency between the app and the extension to work.

| Target Dependencies | Xcode Previews |
|-------------|-------------|
|  <img width="1624" alt="Screenshot 2024-04-06 at 11 45 37" src="https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/7773955/5f373ba6-4d82-45c9-b0ce-885733c67649"> | <img width="1624" alt="Screenshot 2024-04-06 at 11 38 34" src="https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/7773955/ecc2ac15-85c4-4bec-96b7-0a2986b0af9c"> |

Draft with possible fix: https://github.com/MobileNativeFoundation/rules_xcodeproj/pull/2999

**Comment by brentleyjones** [comment]
@andre-alves Can you verify that #3005 fixes this for you?
