### ISSUE TITLE
Feature Request: Ability to configure what generated file types get pulled into the project

### ISSUE THREAD

**Issue by thiagohmcruz** [MobileNativeFoundation/rules_xcodeproj#3014]
As a `rules_ios` user I've noticed that some generated files that are an implementation detail of `rules_ios` are being pulled into Xcode. I'd appreciate the ability to filter those out. 

When generating a project, I noticed some performance issues while editing code in a big codebase with many `rules_ios` frameworks and filtering out unneeded file types has improved the experience for me.

As an example, run this from this repo's root:
```sh
cd examples/rules_ios
bazel run //:xcodeproj-incremental 
```
and note how you can `cmd+shift+o` and find `*_vfs.yaml` or `*.extended.modulemap` files:

![Screenshot 2024-04-16 at 12 45 14 PM](https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/10197663/1cca1d0b-cea6-4eb6-b160-860bca09f3ab)
![Screenshot 2024-04-16 at 12 45 27 PM](https://github.com/MobileNativeFoundation/rules_xcodeproj/assets/10197663/8d01b275-42c2-478e-bf22-20a93e47627a)

We could introduce a global setting here that allows consumers to configure this (say by specifying which generated files `.extension` types are allowed/not allowed to be processed). That could be a feature consumers are supposed to set in their rc files or a setting specified at the `xcodeproj` macro level? For example:
```py
xcodeproj(
  ...
  allowed_generated_file_extensions = [".h", ".m"],
  # or
  exclude_generated_file_extensions = [".yaml", ".modulemap"],
)
```

Thoughts? cc @brentleyjones.

**Comment by thiagohmcruz** [comment]
Alternatively we can simply not process any generated file here.

**Comment by dnkoutso** [comment]
Perhaps a combination of both in which some generated files are automatically not processed and also ability to specify additional file types?

**Comment by thiagohmcruz** [comment]
> Perhaps a combination of both in which some generated files are automatically not processed and also ability to specify additional file types?

@dnkoutso one thing @brentleyjones and I are considering is to use `.is_source` and avoid over collecting [here](https://github.com/MobileNativeFoundation/rules_xcodeproj/blob/main/xcodeproj/internal/files/incremental_input_files.bzl#L113). The problem is that that would also stop collecting potentially desirable `.h` files (say generated headers consumers do want to see in Xcode).

So one idea I'm proposing is to not collect any generated file by default, but allow consumers to set a flag at the `xcodeproj` macro level that "allows generated headers". I think trying to handle file types more generically is probably a feature nobody wants atm since this code path is about headers processing, hence my suggestion to focus on headers collection configuration only. 

But, open for suggestions here, I'm trying to keep this small so we don't try to cover more use cases than needed here until there's a real need. Does that make sense?

**Comment by thiagohmcruz** [comment]
> Perhaps a combination of both in which some generated files are automatically not processed and also ability to specify additional file types?

@dnkoutso We're considering to stop processing generated files and effectively stop over collecting [here](https://github.com/MobileNativeFoundation/rules_xcodeproj/blob/main/xcodeproj/internal/files/incremental_input_files.bzl#L113) instead of trying to come up with a way to expose something configurable to users. 

This is a lot simpler than what I suggested and we can ensure that generated source files continue to be collected somewhere else. We'll keep this issue updated.

**Comment by thiagohmcruz** [comment]
For future reference, this branch illustrates my use case btw: https://github.com/MobileNativeFoundation/rules_xcodeproj/compare/thiago/generated-file-extensions

```sh
cd examples/rules_ios
bazel run //:xcodeproj-incremental
```

My intent is to continue to allow such a project to index `*.pbobjc.m` and `*.pbobjc.h` files since those are relevant to developers and they might want to `cmd+shift+o` these and inspect APIs and types. But, most other files `rules_ios` generates (including but not limited to some `.h` files) are implementation details and not necessary in Xcode.

**Comment by brentleyjones** [comment]
I think #3017 addresses this.

**Comment by thiagohmcruz** [comment]
> I think #3017 addresses this.

It does, thank you!
