### ISSUE TITLE
Feature Request: Co-locate Bazel Generated Files with targets

### ISSUE THREAD

**Issue by sebastianv1** [MobileNativeFoundation/rules_xcodeproj#3037]
Curious how difficult it might be to co-locate the generated files (i.e `genrule` or `swift_proto_compile` sources) under the target's group in Xcode?

For example, in addition to the top-level group `Bazel Generated Files` there could be a generated files group for a target package.

```
.
└── Modules/
    ├── Foo/
    │   ├── Sources/
    │   │   └── Baz.swift
    │   └── Bazel Generated/
    │       ├── <config_ios15>/
    │       │   └── File_Genrule_Generated.swift
    │       └── <config_ios16>/
    │           └── File_Genrule_Generated.swift
    └── Proto/
        ├── proto/
        │   └── test.proto
        └── Bazel Generated/
            └── test.pb.swift  
```

I've abbreviated the true output_base paths for brevity (but noted multiple potential configurations for a generated file with the `config_ios15` and `config_ios16`).

Unsure if this is really feasible, but thought I'd ask since it can currently be a bit tricky to find generated files in Xcode to inspect their contents.

**Comment by brentleyjones** [comment]
@erikkerber Do you want to add to this feature request, since you've personally asked for something similar in the past?

@sebastianv1 this is doable, it just hasn't been a priority since I've only had one other request for it before.

**Comment by sebastianv1** [comment]
@brentleyjones Makes sense and glad to hear it's doable! Any pointers on where I might get started on a potential implementation?

@erikkerber Would love to hear what y'all would find helpful as well.

**Comment by erikkerber** [comment]
I remember mentioning this before, but I don't have anything profound to add to the general idea of putting generated files in an Xcode group that corresponds to the package a generated file shares with a i.e. Swift module.

**Comment by sebastianv1** [comment]
Thanks for the pointers @brentleyjones ! I'll actually have some time to try implementing this.

I did a superficial pass, and one problem I'm thinking about is how we would know which group the `Bazel Generated` files should fall under solely based on the path, and not the Bazel package + label.

For instance, let's say we have `Modules/Foo:genrule_x` and `Modules/Foo/Bar:genrule_y`. I believe the generated `BazelPath` instances would just be `bazel-out/darwin-<x>/bin/Modules/Foo/GenruleX.swift` and `bazel-out/darwin-<x>/bin/Modules/Foo/Bar/GenruleY.swift`? In my mind it makes sense to add a `Bazel Generated` files group next to package's group (if it exists) in Xcode. Maybe it's possible to infer this if a `BUILD.bazel` is present?

**Comment by brentleyjones** [comment]
The generated files have `owner` labels, so we can determine their package, pass that info along somehow, and then place these groups there.

**Comment by sebastianv1** [comment]
Initial draft PR where we could probably continue any implementation specific details: #3047 🙏
