### ISSUE TITLE
Error with PIFCache during Archive Process in Xcode

### ISSUE THREAD

**Issue by jamesryu108** [MobileNativeFoundation/rules_xcodeproj#3045]
Description:

I encountered an error while trying to archive my app in Xcode for TestFlight. The error message is as follows:

`error: PIFCache (/Users/[username]/Library/Developer/Xcode/DerivedData/[project-name]/Build/Intermediates.noindex/ArchiveIntermediates/[project-name]/IntermediateBuildFilesPath/XCBuildData/PIFCache) doesn't exist. If you manually cleared Derived Data, you need to close and re-open the project for the PIFCache to be created again. Using the "Clean Build Folder" command instead (⇧ ⌘ K) won't trigger this error. If this error still happens after re-opening the project, please file a bug report here: https://github.com/MobileNativeFoundation/rules_xcodeproj/issues/new?template=bug.md`

Steps to Reproduce:

Close Xcode.
Delete the Derived Data folder located in the ~/Library/Developer/Xcode/DerivedData/ directory.
Reopen the Xcode project.
Clean the Build Folder using Product > Clean Build Folder.
Attempt to archive the project using Product > Archive.

Expected Result:
The project should archive successfully without any errors.

Actual Result:
The archive process fails with the error message about the missing PIFCache.

Environment:

Xcode Version: 15.2.0
macOS Version: Sonoma 14.5

I have followed the steps to delete Derived Data and re-open the project as suggested, but the error persists. I have also tried using the "Clean Build Folder" command without success. The issue seems to prevent the necessary PIFCache from being recreated.

**Comment by brentleyjones** [comment]
The archive actions isn’t supported. There are more serials in the FAQ.

**Comment by jamesryu108** [comment]
So how can I upload it for TestFlight build?

**Comment by jamesryu108** [comment]
I will try the method specified in FAQ
